#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#define image_0_start_task_initialization_task		(0x58)
#define image_0_initialization_task		(0x58)
#define image_0_start_task_update_fifo_us_read_1st_wakeup_request		(0x528)
#define image_0_update_fifo_us_read_1st_wakeup_request		(0x528)
#define image_0_start_task_ghost_reporting_1st_wakeup_request		(0x16D4)
#define image_0_ghost_reporting_1st_wakeup_request		(0x16D4)
#define image_0_start_task_tx_task_1st_wakeup_request		(0x178)
#define image_0_tx_task_1st_wakeup_request		(0x178)
#define image_0_start_task_epon_update_fifo_read_1st_wakeup_request		(0x7B4)
#define image_0_epon_update_fifo_read_1st_wakeup_request		(0x7B4)
#define image_0_start_task_epon_tx_task_wakeup_request		(0x1A2C)
#define image_0_epon_tx_task_wakeup_request		(0x1A2C)
#define image_0_start_task_budget_allocator_us_1st_wakeup_request		(0xED0)
#define image_0_budget_allocator_us_1st_wakeup_request		(0xED0)
#define image_0_start_task_debug_routine		(0x8C)
#define image_0_debug_routine		(0x8C)
#define image_0_start_task_ds_tx_task_wakeup_request		(0xB6C)
#define image_0_ds_tx_task_wakeup_request		(0xB6C)
#define image_0_start_task_ovl_budget_allocator_1st_wakeup_request		(0x11F0)
#define image_0_ovl_budget_allocator_1st_wakeup_request		(0x11F0)
#define image_0_start_task_flush_task_1st_wakeup_request		(0x154C)
#define image_0_flush_task_1st_wakeup_request		(0x154C)
#define image_0_start_task_update_fifo_ds_read_1st_wakeup_request		(0x8E0)
#define image_0_update_fifo_ds_read_1st_wakeup_request		(0x8E0)
#define image_0_start_task_budget_allocator_ds_1st_wakeup_request		(0xF04)
#define image_0_budget_allocator_ds_1st_wakeup_request		(0xF04)
#define image_0_debug_routine_handler		(0xC)
#define image_0_scheduling_update_status		(0x3D0)
#define image_0_scheduling_action_not_valid		(0x4B8)
#define image_0_basic_scheduler_update_dwrr		(0x8BC)
#define image_0_ds_tx_scheduling_update_status		(0xCD8)
#define image_0_ds_tx_scheduling_action_not_valid		(0xD60)
#define image_0_complex_scheduler_update_dwrr_basic_schedulers		(0xE9C)
#define image_0_complex_scheduler_update_dwrr_queues		(0xEAC)
#define image_0_basic_rate_limiter_complex_scheduler		(0x12C4)
#define image_0_basic_rate_limiter_basic_scheduler_no_cs		(0x12F4)
#define image_0_basic_rate_limiter_queue_with_cs_bs		(0x1324)
#define image_0_basic_rate_limiter_queue_with_bs		(0x1374)
#define image_0_ovl_rate_limiter		(0x13A8)
#define image_0_complex_rate_limiter_queue_sir		(0x13BC)
#define image_0_complex_rate_limiter_queue_pir		(0x13F4)
#define image_0_complex_rate_limiter_basic_scheduler_sir		(0x142C)
#define image_0_complex_rate_limiter_basic_scheduler_pir		(0x1464)

#endif
