#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#define image_1_start_task_initialization_task		(0x18)
#define image_1_initialization_task		(0x18)
#define image_1_start_task_cpu_rx_wakeup_request		(0x1178)
#define image_1_cpu_rx_wakeup_request		(0x1178)
#define image_1_start_task_direct_processing_wakeup_request		(0x14E0)
#define image_1_direct_processing_wakeup_request		(0x14E0)
#define image_1_start_task_debug_routine		(0x4C)
#define image_1_debug_routine		(0x4C)
#define image_1_start_task_gpon_control_wakeup_request		(0x1540)
#define image_1_gpon_control_wakeup_request		(0x1540)
#define image_1_start_task_cpu_rx_update_fifo_wakeup_request		(0x1140)
#define image_1_cpu_rx_update_fifo_wakeup_request		(0x1140)
#define image_1_start_task_cpu_recycle_wakeup_request		(0x16FC)
#define image_1_cpu_recycle_wakeup_request		(0x16FC)
#define image_1_start_task_interrupt_coalescing_1st_wakeup_request		(0x1854)
#define image_1_interrupt_coalescing_1st_wakeup_request		(0x1854)
#define image_1_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request		(0x1658)
#define image_1_cpu_rx_meter_budget_allocator_1st_wakeup_request		(0x1658)
#define image_1_start_task_dhd_tx_post_wakeup_request		(0x2AC)
#define image_1_dhd_tx_post_wakeup_request		(0x2AC)
#define image_1_start_task_dhd_tx_post_update_fifo_wakeup_request		(0x254)
#define image_1_dhd_tx_post_update_fifo_wakeup_request		(0x254)
#define image_1_start_task_dhd_timer_1st_wakeup_request		(0x138)
#define image_1_dhd_timer_1st_wakeup_request		(0x138)
#define image_1_start_task_dhd_mcast_wakeup_request		(0xB68)
#define image_1_dhd_mcast_wakeup_request		(0xB68)
#define image_1_start_task_dhd_mcast_update_fifo_wakeup_request		(0xB30)
#define image_1_dhd_mcast_update_fifo_wakeup_request		(0xB30)
#define image_1_start_task_cpu_rx_copy_wakeup_request		(0xD94)
#define image_1_cpu_rx_copy_wakeup_request		(0xD94)
#define image_1_start_task_cpu_rx_copy_update_fifo_wakeup_request		(0xD5C)
#define image_1_cpu_rx_copy_update_fifo_wakeup_request		(0xD5C)
#define image_1_debug_routine_handler		(0xC)

#endif
