#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#define image_0_start_task_initialization_task		(0x18)
#define image_0_initialization_task		(0x18)
#define image_0_start_task_update_fifo_read_1st_wakeup_request		(0xCC8)
#define image_0_update_fifo_read_1st_wakeup_request		(0xCC8)
#define image_0_start_task_tx_task_1st_wakeup_request		(0x178)
#define image_0_tx_task_1st_wakeup_request		(0x178)
#define image_0_tx_task_wakeup_request		(0x178)
#define image_0_start_task_flush_task_1st_wakeup_request		(0x660)
#define image_0_flush_task_1st_wakeup_request		(0x660)
#define image_0_start_task_budget_allocator_1st_wakeup_request		(0x764)
#define image_0_budget_allocator_1st_wakeup_request		(0x764)
#define image_0_start_task_debug_routine		(0x8C)
#define image_0_debug_routine		(0x8C)
#define image_0_debug_routine_handler		(0xC)
#define image_0_scheduling_update_status		(0x3A4)
#define image_0_scheduling_action_not_valid		(0x444)
#define image_0_basic_scheduler_update_dwrr		(0x554)
#define image_0_complex_scheduler_update_dwrr_basic_schedulers		(0x640)
#define image_0_complex_scheduler_update_dwrr_queues		(0x650)
#define image_0_basic_rate_limiter_complex_scheduler		(0xA4C)
#define image_0_basic_rate_limiter_basic_scheduler_no_cs		(0xA7C)
#define image_0_basic_rate_limiter_queue_with_cs_bs		(0xAAC)
#define image_0_basic_rate_limiter_queue_with_bs		(0xAFC)
#define image_0_complex_rate_limiter_queue_sir		(0xB30)
#define image_0_complex_rate_limiter_queue_pir		(0xB68)
#define image_0_complex_rate_limiter_basic_scheduler_sir		(0xBA0)
#define image_0_complex_rate_limiter_basic_scheduler_pir		(0xBD8)

#endif
