// ****************************************************************************
//
// Copyright (c) 2009 Broadcom Corporation
//
// This program is the proprietary software of Broadcom Corporation and/or
// its licensors, and may only be used, duplicated, modified or distributed
// pursuant to the terms and conditions of a separate, written license
// agreement executed between you and Broadcom (an "Authorized License").
// Except as set forth in an Authorized License, Broadcom grants no license
// (express or implied), right to use, or waiver of any kind with respect to
// the Software, and Broadcom expressly reserves all rights in and to the
// Software and all intellectual property rights therein.  IF YOU HAVE NO
// AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY,
// AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE
// SOFTWARE.  
//
// Except as expressly set forth in the Authorized License,
//
// 1.     This program, including its structure, sequence and organization,
// constitutes the valuable trade secrets of Broadcom, and you shall use all
// reasonable efforts to protect the confidentiality thereof, and to use this
// information only in connection with your use of Broadcom integrated circuit
// products.
//
// 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
// "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
// OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
// RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
// IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
// A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
// ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
// THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
//
// 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
// OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
// INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
// RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
// HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
// EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
// WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
// FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
//
// ****************************************************************************
//
//  Filename:         apm_blockdef.h
//  Generated by:     RDB Utility
//  Creation Date:    12/4/2009
//  Command Line:     rdb.pl bcm3382_a0.rdb2 -header rdb_output/headers_borked -camelcase -nounroll --addrtest=rdb_output/test_borked.c -R
// ****************************************************************************
//
// IMPORTANT: DO NOT MODIFY, THIS IS AN AUTOGENERATED FILE. 
// Please modify the source .rdb file instead if you need to change this file. 
// Contact Jeff Bauch if you need more information.
//
// ****************************************************************************
#ifndef APM_BLOCKDEF_H__
#define APM_BLOCKDEF_H__

#include "iudma_ctrl.h"
#include "hvg_base.h"
#include "apm_base.h"
#include "apm_pcm.h"

typedef struct {
  ApmBaseApmBaseApmBase          ApmBase;
  uint8                          Pad0[0x8c];
  ApmPcmApmPcmApmPcm             ApmPcm;
  uint8                          Pad1[0x80];
  HvgBaseHvgBaseHvgBase          HvgBase;
  uint8                          Pad2[0x370];
  IudmaCtrlCtrlRegs              ApmDmaCtrl;
  uint8                          Pad3[0xdc];
  IudmaCtrlChannelCfgRegs        ApmDmaCh1;
  IudmaCtrlChannelCfgRegs        ApmDmaCh2;
  IudmaCtrlChannelCfgRegs        ApmDmaCh3;
  IudmaCtrlChannelCfgRegs        ApmDmaCh4;
  IudmaCtrlChannelCfgRegs        ApmDmaCh5;
  IudmaCtrlChannelCfgRegs        ApmDmaCh6;
  uint8                          Pad4[0xa0];
  IudmaCtrlChannelCfgStram       ApmDmaCh1State;
  IudmaCtrlChannelCfgStram       ApmDmaCh2State;
  IudmaCtrlChannelCfgStram       ApmDmaCh3State;
  IudmaCtrlChannelCfgStram       ApmDmaCh4State;
  IudmaCtrlChannelCfgStram       ApmDmaCh5State;
  IudmaCtrlChannelCfgStram       ApmDmaCh6State;
  uint8                          Pad5[0x5a0];
} Apm;

#endif 



