# File: bcmdrivers/opensource/char/tzdrv/cpuload_tdrv/impl1/Makefile
#
# Makefile for the cpuload_tdrv driver
#

obj-m += cpuload_tdrv.o

astra_subdir=$(BUILD_DIR)/secureos/astra

EXTRA_CFLAGS += \
	-I$(astra_subdir)/common/include \
	-I$(src)/../../bcm_astra/bcm9$(BRCM_CHIP)


