#ifndef RUNNER_C_CODE_ADDRESSES
#define RUNNER_C_CODE_ADDRESSES

#define runner_c_start_task_initialization_task		(0x14)
#define runner_c_initialization_task		(0x14)
#define runner_c_start_task_timer_scheduler_set		(0x840)
#define runner_c_timer_scheduler_set		(0x840)
#define runner_c_start_task_lan_tx_wakeup_request		(0x450)
#define runner_c_lan_tx_wakeup_request		(0x450)
#define runner_c_start_task_cpu_tx_wakeup_request		(0xAD8)
#define runner_c_cpu_tx_wakeup_request		(0xAD8)
#define runner_c_start_task_lan_enqueue_ih_wakeup_request		(0x1C4)
#define runner_c_lan_enqueue_ih_wakeup_request		(0x1C4)
#define runner_c_start_task_lan_enqueue_pd_wakeup_request		(0x208)
#define runner_c_lan_enqueue_pd_wakeup_request		(0x208)
#define runner_c_start_task_multicast_lan_enqueue_wakeup_request		(0x258)
#define runner_c_multicast_lan_enqueue_wakeup_request		(0x258)
#define runner_c_start_task_wlan_mcast_wakeup_request		(0x30FC)
#define runner_c_wlan_mcast_wakeup_request		(0x30FC)
#define runner_c_start_task_cpu_rx_int_coalesce_timer_1st_wakeup_request		(0xA20)
#define runner_c_cpu_rx_int_coalesce_timer_1st_wakeup_request		(0xA20)
#define runner_c_start_task_debug_routine		(0xDC)
#define runner_c_debug_routine		(0xDC)
#define runner_c_start_task_gso_wakeup_request		(0x1E48)
#define runner_c_gso_wakeup_request		(0x1E48)
#define runner_c_start_task_spdsvc_timer_1st_wakeup_request		(0x1078)
#define runner_c_spdsvc_timer_1st_wakeup_request		(0x1078)
#define runner_c_start_task_free_skb_index_wakeup_request		(0x9B0)
#define runner_c_free_skb_index_wakeup_request		(0x9B0)
#define runner_c_start_task_service_queue_dequeue_wakeup_request		(0x3A18)
#define runner_c_service_queue_dequeue_wakeup_request		(0x3A18)
#define runner_c_start_task_service_queue_enqueue_wakeup_request		(0x3AE8)
#define runner_c_service_queue_enqueue_wakeup_request		(0x3AE8)
#define runner_c_ds_rate_limiter_budget_allocate		(0x8C0)
#define runner_c_ds_service_queue_rate_limiter_budget_allocate		(0x97C)
#define runner_c_schedule_free_skb_index		(0x994)

#endif
