#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x1864)
#define runner_d_timer_scheduler_set		(0x1864)
#define runner_d_start_task_flow_cache_wakeup_request		(0xA18)
#define runner_d_flow_cache_wakeup_request		(0xA18)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x161C)
#define runner_d_lan_dispatch_wakeup_request		(0x161C)
#define runner_d_start_task_lan_cpu_wakeup_request		(0x154)
#define runner_d_lan_cpu_wakeup_request		(0x154)
#define runner_d_start_task_lan_normal_wakeup_request		(0x188)
#define runner_d_lan_normal_wakeup_request		(0x188)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x19E0)
#define runner_d_free_skb_index_wakeup_request		(0x19E0)
#define runner_d_free_skb_index_tx_abs_done		(0x19E0)
#define runner_d_start_task_dhd_rx_complete_wakeup_request		(0x1AB4)
#define runner_d_dhd_rx_complete_wakeup_request		(0x1AB4)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x103C)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x10AC)
#define runner_d_gpe_sop_push_replace_sram_64		(0x10C0)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x10D4)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x10E8)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x1158)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x11A8)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x11E4)
#define runner_d_gpe_replace_pointer_32_ddr		(0x1234)
#define runner_d_gpe_replace_pointer_32_sram		(0x1258)
#define runner_d_gpe_replace_pointer_64_sram		(0x127C)
#define runner_d_gpe_replace_16		(0x12A0)
#define runner_d_gpe_replace_32		(0x12D4)
#define runner_d_gpe_replace_bits_16		(0x12F8)
#define runner_d_gpe_copy_add_16_cl		(0x1324)
#define runner_d_gpe_copy_add_16_sram		(0x1330)
#define runner_d_gpe_copy_bits_16_cl		(0x1378)
#define runner_d_gpe_copy_bits_16_sram		(0x1384)
#define runner_d_gpe_insert_16		(0x13CC)
#define runner_d_gpe_delete_16		(0x1434)
#define runner_d_gpe_decrement_8		(0x1474)
#define runner_d_gpe_apply_icsum_16		(0x1498)
#define runner_d_gpe_apply_icsum_nz_16		(0x14BC)
#define runner_d_gpe_compute_csum_16_cl		(0x14F8)
#define runner_d_gpe_compute_csum_16_sram		(0x1504)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x18E4)
#define runner_d_upstream_quasi_budget_allocate		(0x1964)
#define runner_d_schedule_free_skb_index		(0x19C4)

#endif
