/*
   Copyright (c) 2015 Broadcom
   All Rights Reserved

    <:label-BRCM:2015:DUAL/GPL:standard

    Unless you and Broadcom execute a separate written software license
    agreement governing use of this software, this software is licensed
    to you under the terms of the GNU General Public License version 2
    (the "GPL"), available at http://www.broadcom.com/licenses/GPLv2.php,
    with the following added to such license:

       As a special exception, the copyright holders of this software give
       you permission to link this software with independent modules, and
       to copy and distribute the resulting executable under terms of your
       choice, provided that you also meet, for each linked independent
       module, the terms and conditions of the license of that module.
       An independent module is a module which is not derived from this
       software.  The special exception does not apply to any modifications
       of the software.

    Not withstanding the above, under no circumstances may you combine
    this software in any way with any other Broadcom software provided
    under a license other than the GPL, without Broadcom's express prior
    written consent.

:>
*/



/* This is an automated file. Do not edit its contents. */


#include "rdd.h"
#include "ru_types.h"

#include "rdd_data_structures_auto.h"

/* >>>RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */
uint32_t RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1400,
	0x1400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1d00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1d40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_REGISTERS_BUFFER_ADDRESS_ARR */
uint32_t RDD_REGISTERS_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1d80,
	0x2e00,
	0x2208,
	0x2580,
	0x1a08,
	0x1a08,
};
/* <<<RDD_REGISTERS_BUFFER_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_RX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_RX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2800,
	INVALID_TABLE_ADDRESS,
	0x1800,
	0x0,
	0x1000,
	0x1000,
};
/* <<<RDD_RX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2a94,
	0x2ae2,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2a96,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2a98,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR */
uint32_t RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2aa0,
	0x1da0,
	0x1aa0,
	0x2a0,
	0x12a0,
	0x12a0,
};
/* <<<RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ac0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ae2,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */


/* >>>RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ae3,
	0x2ae7,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_TASK_IDX_ADDRESS_ARR */
uint32_t RDD_TASK_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ae4,
	0x2eb4,
	0x2364,
	0x29a4,
	0x1b24,
	0x1b24,
};
/* <<<RDD_TASK_IDX_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ae8,
	INVALID_TABLE_ADDRESS,
	0x2b68,
	0x2968,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2af0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_COUNTER_MAX_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_COUNTER_MAX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2afc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_COUNTER_MAX_ADDRESS_ARR */


/* >>>RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2afe,
	0x2ed4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b20,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */


/* >>>RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */
uint32_t RDD_SRAM_DUMMY_STORE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b34,
	0x2ed6,
	0x23a6,
	0x29ad,
	0x1b66,
	0x1b66,
};
/* <<<RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR */
uint32_t RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b35,
	0x2ed7,
	0x23a7,
	0x2b3c,
	0x1b67,
	0x1b67,
};
/* <<<RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR */


/* >>>RDD_MAC_TYPE_ADDRESS_ARR */
uint32_t RDD_MAC_TYPE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b36,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_MAC_TYPE_ADDRESS_ARR */


/* >>>RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b37,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */
uint32_t RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b38,
	0x2ae8,
	0x2288,
	0xa08,
	0x1608,
	0x1608,
};
/* <<<RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */


/* >>>RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b40,
	0x2e80,
	INVALID_TABLE_ADDRESS,
	0x29c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b60,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_ACB_PORT_STATUS_TABLE_ADDRESS_ARR */
uint32_t RDD_ACB_PORT_STATUS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b78,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_ACB_PORT_STATUS_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */


/* >>>RDD_SCRATCH_ADDRESS_ARR */
uint32_t RDD_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b98,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SCRATCH_ADDRESS_ARR */


/* >>>RDD_MIRRORING_SCRATCH_ADDRESS_ARR */
uint32_t RDD_MIRRORING_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bb8,
	0x2eb8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_MIRRORING_SCRATCH_ADDRESS_ARR */


/* >>>RDD_ACB_PACKET_SENT_PD_COPY_ADDRESS_ARR */
uint32_t RDD_ACB_PACKET_SENT_PD_COPY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_ACB_PACKET_SENT_PD_COPY_ADDRESS_ARR */


/* >>>RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bd0,
	0x2f40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2be0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bf0,
	INVALID_TABLE_ADDRESS,
	0x2b70,
	0x2a30,
	0x1b70,
	0x1b70,
};
/* <<<RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */
uint32_t RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c00,
	0x2c00,
	0x2400,
	0x2000,
	0x1c00,
	0x1c00,
};
/* <<<RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_FPM_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e20,
	0x2f50,
	0x2b90,
	0x2b30,
	0x1be0,
	0x1be0,
};
/* <<<RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e30,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_DS_TM_EGRESS_PORT_RR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_EGRESS_PORT_RR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2f00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_EGRESS_PORT_RR_TABLE_ADDRESS_ARR */


/* >>>RDD_DEBUG_TRACE_ADDRESS_ARR */
uint32_t RDD_DEBUG_TRACE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x3e00,
	0x3e00,
	0x3e00,
	0x3e00,
	0x3e00,
	0x3e00,
};
/* <<<RDD_DEBUG_TRACE_ADDRESS_ARR */


/* >>>RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1d00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1dc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2a00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2aa0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */


/* >>>RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ab4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ab8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ac0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ae4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ae6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */


/* >>>RDD_XGPON_REPORT_TABLE_ADDRESS_ARR */
uint32_t RDD_XGPON_REPORT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2af0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_XGPON_REPORT_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2b00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2b80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ea0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ec0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */


/* >>>RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ed8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ee0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_FIFO_SIZE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_FIFO_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ef4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_FIFO_SIZE_ADDRESS_ARR */


/* >>>RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ef5,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ef6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ef8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR */


/* >>>RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR */
uint32_t RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f10,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f20,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f30,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR */
uint32_t RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f60,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_DS_PACKET_BUFFER_ADDRESS_ARR */
uint32_t RDD_DS_PACKET_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x0,
	0x1000,
	0x0,
	0x0,
};
/* <<<RDD_DS_PACKET_BUFFER_ADDRESS_ARR */


/* >>>RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_DS_WAN_UDP_FILTER_CONTROL_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_WAN_UDP_FILTER_CONTROL_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1a94,
	0x294,
	0x1294,
	0x1294,
};
/* <<<RDD_DS_WAN_UDP_FILTER_CONTROL_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_REPLY_ADDRESS_ARR */
uint32_t RDD_FPM_REPLY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1a98,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_FPM_REPLY_ADDRESS_ARR */


/* >>>RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */
uint32_t RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1ac0,
	0x2c0,
	0x12c0,
	0x12c0,
};
/* <<<RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */


/* >>>RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR */
uint32_t RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1b00,
	0x300,
	0x1300,
	0x1300,
};
/* <<<RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR */


/* >>>RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1c00,
	0x800,
	0x1400,
	0x1400,
};
/* <<<RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1e08,
	0x298,
	0x1298,
	0x1298,
};
/* <<<RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_WAN_UDP_FILTER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_WAN_UDP_FILTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1e10,
	0xa10,
	0x1610,
	0x1610,
};
/* <<<RDD_DS_WAN_UDP_FILTER_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1e20,
	0xa20,
	0x1620,
	0x1620,
};
/* <<<RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1e40,
	0x7c0,
	0x1640,
	0x1640,
};
/* <<<RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1e80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_PBIT_TO_GEM_TABLE_ADDRESS_ARR */
uint32_t RDD_PBIT_TO_GEM_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1ec0,
	0xa40,
	0x1680,
	0x1680,
};
/* <<<RDD_PBIT_TO_GEM_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1f00,
	0xf00,
	0x1700,
	0x1700,
};
/* <<<RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR */


/* >>>RDD_DUAL_STACK_LITE_TABLE_ADDRESS_ARR */
uint32_t RDD_DUAL_STACK_LITE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1f80,
	0xbc0,
	0x16c0,
	0x16c0,
};
/* <<<RDD_DUAL_STACK_LITE_TABLE_ADDRESS_ARR */


/* >>>RDD_GPE_COMMAND_PRIMITIVE_TABLE_ADDRESS_ARR */
uint32_t RDD_GPE_COMMAND_PRIMITIVE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1fc0,
	0xe40,
	0x1780,
	0x1780,
};
/* <<<RDD_GPE_COMMAND_PRIMITIVE_TABLE_ADDRESS_ARR */


/* >>>RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2000,
	0xc00,
	0x1800,
	0x1800,
};
/* <<<RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_BROADCOM_SWITCH_PORT_TO_RX_FLOW_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_BROADCOM_SWITCH_PORT_TO_RX_FLOW_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2290,
	0xb90,
	0x17f0,
	0x17f0,
};
/* <<<RDD_BROADCOM_SWITCH_PORT_TO_RX_FLOW_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22a0,
	0x2740,
	0x1aa0,
	0x1aa0,
};
/* <<<RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2300,
	0x27c0,
	0x17c0,
	0x17c0,
};
/* <<<RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_PROCESSING_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */
uint32_t RDD_PROCESSING_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2328,
	0xe08,
	0x17e8,
	0x17e8,
};
/* <<<RDD_PROCESSING_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_LOOKUP_PORT_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_LOOKUP_PORT_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2330,
	0xe10,
	0x1a90,
	0x1a90,
};
/* <<<RDD_VPORT_TO_LOOKUP_PORT_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */
uint32_t RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2340,
	0x2940,
	0x1b00,
	0x1b00,
};
/* <<<RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */


/* >>>RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2368,
	0xff8,
	0x1a88,
	0x1a88,
};
/* <<<RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2370,
	0x27f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2380,
	0x2980,
	0x1b40,
	0x1b40,
};
/* <<<RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_FORCE_DSCP_ADDRESS_ARR */
uint32_t RDD_FORCE_DSCP_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23a2,
	0x29a2,
	0x1b62,
	0x1b62,
};
/* <<<RDD_FORCE_DSCP_ADDRESS_ARR */


/* >>>RDD_CORE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_CORE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23a3,
	0x29a3,
	0x1b63,
	0x1b63,
};
/* <<<RDD_CORE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23a4,
	0x29be,
	0x1b64,
	0x1b64,
};
/* <<<RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_NULL_BUFFER_ADDRESS_ARR */
uint32_t RDD_NULL_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23a8,
	0x27e8,
	0x1b28,
	0x1b28,
};
/* <<<RDD_NULL_BUFFER_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23b0,
	0x2970,
	0x1b30,
	0x1b30,
};
/* <<<RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR */
uint32_t RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23e0,
	0xba0,
	0x1b80,
	0x1b80,
};
/* <<<RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2600,
	0x600,
	0x1e00,
	0x1e00,
};
/* <<<RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR */
uint32_t RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27e0,
	0xe20,
	0x1ba0,
	0x1ba0,
};
/* <<<RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR */


/* >>>RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR */
uint32_t RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2800,
	0x2200,
	0x2000,
	0x2000,
};
/* <<<RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2980,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_HANDLER_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_HANDLER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29a0,
	0x27a0,
	0x1bc0,
	0x1bc0,
};
/* <<<RDD_TCAM_IC_HANDLER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29e0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_RECYCLE_RING_ID_ADDRESS_ARR */
uint32_t RDD_CPU_TX_RECYCLE_RING_ID_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29ec,
	0x2b3d,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_RECYCLE_RING_ID_ADDRESS_ARR */


/* >>>RDD_IC_DEBUG_COUNTER_MODE_ADDRESS_ARR */
uint32_t RDD_IC_DEBUG_COUNTER_MODE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29ed,
	0x2b3e,
	0x1b6d,
	0x1b6d,
};
/* <<<RDD_IC_DEBUG_COUNTER_MODE_ADDRESS_ARR */


/* >>>RDD_CPU_REDIRECT_MODE_ADDRESS_ARR */
uint32_t RDD_CPU_REDIRECT_MODE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29ee,
	0x2b3f,
	0x1b6e,
	0x1b6e,
};
/* <<<RDD_CPU_REDIRECT_MODE_ADDRESS_ARR */


/* >>>RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29ef,
	0x2b9f,
	0x1b6f,
	0x1b6f,
};
/* <<<RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29fc,
	0x2ba2,
	0x1bec,
	0x1bec,
};
/* <<<RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR */


/* >>>RDD_VPORT_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a00,
	0x2400,
	0x2200,
	0x2200,
};
/* <<<RDD_VPORT_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b40,
	0x29e0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b50,
	0x29f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b60,
	0x2928,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b80,
	0x2b80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b88,
	0x29a8,
	0x1b68,
	0x1b68,
};
/* <<<RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ba0,
	0x2b68,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR */
uint32_t RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ba8,
	0x2b78,
	0x1bf0,
	0x1bf0,
};
/* <<<RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR */


/* >>>RDD_IPTV_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bb0,
	0x2b88,
	0x1bf8,
	0x1bf8,
};
/* <<<RDD_IPTV_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR */
uint32_t RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bb8,
	0x2b90,
	0x1fc0,
	0x1fc0,
};
/* <<<RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR */


/* >>>RDD_NAT_CACHE_CFG_ADDRESS_ARR */
uint32_t RDD_NAT_CACHE_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bc0,
	0x2b98,
	0x1fc8,
	0x1fc8,
};
/* <<<RDD_NAT_CACHE_CFG_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_CFG_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bc8,
	0x2ba0,
	0x1fd0,
	0x1fd0,
};
/* <<<RDD_INGRESS_FILTER_CFG_ADDRESS_ARR */


/* >>>RDD_TX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c00,
	0x2600,
	0x2400,
	0x2400,
};
/* <<<RDD_TX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d80,
	0x2c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e00,
	0x2800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f00,
	0x2c80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */


/* >>>RDD_FC_FLOW_IP_ADDRESSES_TABLE_ADDRESS_ARR */
uint32_t RDD_FC_FLOW_IP_ADDRESSES_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3d00,
	0x3d00,
	0x3d00,
	0x3d00,
};
/* <<<RDD_FC_FLOW_IP_ADDRESSES_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xb00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2380,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2540,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2900,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2930,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2964,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29ae,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29b0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29bc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a20,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_TO_TC_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_TO_TC_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a60,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_TO_TC_ADDRESS_ARR */


/* >>>RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_TC_TO_CPU_RXQ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2aa0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ae0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b20,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b70,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */

