#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#define image_0_start_task_initialization_task		(0x58)
#define image_0_initialization_task		(0x58)
#define image_0_start_task_update_fifo_read_1st_wakeup_request		(0xB00)
#define image_0_update_fifo_read_1st_wakeup_request		(0xB00)
#define image_0_start_task_direct_processing_wakeup_request		(0x884)
#define image_0_direct_processing_wakeup_request		(0x884)
#define image_0_start_task_budget_allocator_1st_wakeup_request		(0x274)
#define image_0_budget_allocator_1st_wakeup_request		(0x274)
#define image_0_start_task_debug_routine		(0x8C)
#define image_0_debug_routine		(0x8C)
#define image_0_start_task_gpon_control_wakeup_request		(0x8E4)
#define image_0_gpon_control_wakeup_request		(0x8E4)
#define image_0_start_task_ds_tx_task_wakeup_request		(0xDE0)
#define image_0_ds_tx_task_wakeup_request		(0xDE0)
#define image_0_start_task_flush_task_1st_wakeup_request		(0x9FC)
#define image_0_flush_task_1st_wakeup_request		(0x9FC)
#define image_0_debug_routine_handler		(0xC)
#define image_0_complex_scheduler_update_dwrr_basic_schedulers		(0x254)
#define image_0_complex_scheduler_update_dwrr_queues		(0x264)
#define image_0_basic_rate_limiter_complex_scheduler		(0x55C)
#define image_0_basic_rate_limiter_basic_scheduler_no_cs		(0x58C)
#define image_0_basic_rate_limiter_queue_with_cs_bs		(0x5BC)
#define image_0_basic_rate_limiter_queue_with_bs		(0x60C)
#define image_0_complex_rate_limiter_queue_sir		(0x640)
#define image_0_complex_rate_limiter_queue_pir		(0x678)
#define image_0_complex_rate_limiter_basic_scheduler_sir		(0x6B0)
#define image_0_complex_rate_limiter_basic_scheduler_pir		(0x6E8)
#define image_0_basic_scheduler_update_dwrr		(0x7BC)
#define image_0_ds_tx_scheduling_update_status		(0xFF0)
#define image_0_ds_tx_scheduling_action_not_valid		(0x10E4)

#endif
