#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#define image_2_start_task_initialization_task		(0x18)
#define image_2_initialization_task		(0x18)
#define image_2_start_task_ghost_reporting_1st_wakeup_request		(0x138)
#define image_2_ghost_reporting_1st_wakeup_request		(0x138)
#define image_2_start_task_cpu_rx_wakeup_request		(0xA4C)
#define image_2_cpu_rx_wakeup_request		(0xA4C)
#define image_2_start_task_cpu_tx_wakeup_request		(0x510)
#define image_2_cpu_tx_wakeup_request		(0x510)
#define image_2_start_task_direct_processing_wakeup_request		(0x1164)
#define image_2_direct_processing_wakeup_request		(0x1164)
#define image_2_start_task_debug_routine		(0x4C)
#define image_2_debug_routine		(0x4C)
#define image_2_start_task_gpon_control_wakeup_request		(0x11C4)
#define image_2_gpon_control_wakeup_request		(0x11C4)
#define image_2_start_task_cpu_rx_update_fifo_wakeup_request		(0xA14)
#define image_2_cpu_rx_update_fifo_wakeup_request		(0xA14)
#define image_2_start_task_cpu_tx_update_fifo_wakeup_request		(0x4D0)
#define image_2_cpu_tx_update_fifo_wakeup_request		(0x4D0)
#define image_2_start_task_cpu_recycle_wakeup_request		(0x12DC)
#define image_2_cpu_recycle_wakeup_request		(0x12DC)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request		(0x1434)
#define image_2_interrupt_coalescing_1st_wakeup_request		(0x1434)
#define image_2_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request		(0x14C0)
#define image_2_cpu_rx_meter_budget_allocator_1st_wakeup_request		(0x14C0)
#define image_2_start_task_cpu_rx_copy_wakeup_request		(0xDB8)
#define image_2_cpu_rx_copy_wakeup_request		(0xDB8)
#define image_2_start_task_cpu_rx_copy_update_fifo_wakeup_request		(0xD80)
#define image_2_cpu_rx_copy_update_fifo_wakeup_request		(0xD80)
#define image_2_debug_routine_handler		(0xC)

#endif
