#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#define image_3_start_task_initialization_task		(0x18)
#define image_3_initialization_task		(0x18)
#define image_3_start_task_update_fifo_read_1st_wakeup_request		(0xF04)
#define image_3_update_fifo_read_1st_wakeup_request		(0xF04)
#define image_3_start_task_tx_task_1st_wakeup_request		(0x178)
#define image_3_tx_task_1st_wakeup_request		(0x178)
#define image_3_start_task_epon_update_fifo_read_1st_wakeup_request		(0x1190)
#define image_3_epon_update_fifo_read_1st_wakeup_request		(0x1190)
#define image_3_start_task_epon_tx_task_wakeup_request		(0x528)
#define image_3_epon_tx_task_wakeup_request		(0x528)
#define image_3_start_task_flush_task_1st_wakeup_request		(0x7D4)
#define image_3_flush_task_1st_wakeup_request		(0x7D4)
#define image_3_start_task_budget_allocator_1st_wakeup_request		(0x8BC)
#define image_3_budget_allocator_1st_wakeup_request		(0x8BC)
#define image_3_start_task_debug_routine		(0x8C)
#define image_3_debug_routine		(0x8C)
#define image_3_start_task_ovl_budget_allocator_1st_wakeup_request		(0xBA8)
#define image_3_ovl_budget_allocator_1st_wakeup_request		(0xBA8)
#define image_3_debug_routine_handler		(0xC)
#define image_3_scheduling_update_status		(0x3D0)
#define image_3_scheduling_action_not_valid		(0x4B8)
#define image_3_basic_scheduler_update_dwrr		(0x698)
#define image_3_complex_scheduler_update_dwrr_basic_schedulers		(0x7A0)
#define image_3_complex_scheduler_update_dwrr_queues		(0x7B0)
#define image_3_basic_rate_limiter_complex_scheduler		(0xC7C)
#define image_3_basic_rate_limiter_basic_scheduler_no_cs		(0xCAC)
#define image_3_basic_rate_limiter_queue_with_cs_bs		(0xCDC)
#define image_3_basic_rate_limiter_queue_with_bs		(0xD2C)
#define image_3_ovl_rate_limiter		(0xD60)
#define image_3_complex_rate_limiter_queue_sir		(0xD74)
#define image_3_complex_rate_limiter_queue_pir		(0xDAC)
#define image_3_complex_rate_limiter_basic_scheduler_sir		(0xDE4)
#define image_3_complex_rate_limiter_basic_scheduler_pir		(0xE1C)

#endif
