#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#define image_0_start_task_initialization_task		(0x18)
#define image_0_initialization_task		(0x18)
#define image_0_start_task_update_fifo_read_1st_wakeup_request		(0x8D0)
#define image_0_update_fifo_read_1st_wakeup_request		(0x8D0)
#define image_0_start_task_tx_task_1st_wakeup_request		(0xE38)
#define image_0_tx_task_1st_wakeup_request		(0xE38)
#define image_0_tx_task_wakeup_request		(0xE38)
#define image_0_start_task_g9991_tx_task_1st_wakeup_request		(0xB64)
#define image_0_g9991_tx_task_1st_wakeup_request		(0xB64)
#define image_0_start_task_flush_task_1st_wakeup_request		(0x274)
#define image_0_flush_task_1st_wakeup_request		(0x274)
#define image_0_start_task_budget_allocator_1st_wakeup_request		(0x378)
#define image_0_budget_allocator_1st_wakeup_request		(0x378)
#define image_0_start_task_g9991_flow_control_wakeup_request		(0xD64)
#define image_0_g9991_flow_control_wakeup_request		(0xD64)
#define image_0_start_task_debug_routine		(0x8C)
#define image_0_debug_routine		(0x8C)
#define image_0_start_task_g9991_system_port_wakeup_request		(0x129C)
#define image_0_g9991_system_port_wakeup_request		(0x129C)
#define image_0_debug_routine_handler		(0xC)
#define image_0_complex_scheduler_update_dwrr_basic_schedulers		(0x254)
#define image_0_complex_scheduler_update_dwrr_queues		(0x264)
#define image_0_basic_rate_limiter_complex_scheduler		(0x660)
#define image_0_basic_rate_limiter_basic_scheduler_no_cs		(0x690)
#define image_0_basic_rate_limiter_queue_with_cs_bs		(0x6C0)
#define image_0_basic_rate_limiter_queue_with_bs		(0x710)
#define image_0_complex_rate_limiter_queue_sir		(0x744)
#define image_0_complex_rate_limiter_queue_pir		(0x77C)
#define image_0_complex_rate_limiter_basic_scheduler_sir		(0x7B4)
#define image_0_complex_rate_limiter_basic_scheduler_pir		(0x7EC)
#define image_0_basic_scheduler_update_dwrr		(0x8C0)
#define image_0_scheduling_update_status		(0x1068)
#define image_0_scheduling_action_not_valid		(0x1184)

#endif
