/*
   Copyright (c) 2015 Broadcom
   All Rights Reserved

    <:label-BRCM:2015:DUAL/GPL:standard

    Unless you and Broadcom execute a separate written software license
    agreement governing use of this software, this software is licensed
    to you under the terms of the GNU General Public License version 2
    (the "GPL"), available at http://www.broadcom.com/licenses/GPLv2.php,
    with the following added to such license:

       As a special exception, the copyright holders of this software give
       you permission to link this software with independent modules, and
       to copy and distribute the resulting executable under terms of your
       choice, provided that you also meet, for each linked independent
       module, the terms and conditions of the license of that module.
       An independent module is a module which is not derived from this
       software.  The special exception does not apply to any modifications
       of the software.

    Not withstanding the above, under no circumstances may you combine
    this software in any way with any other Broadcom software provided
    under a license other than the GPL, without Broadcom's express prior
    written consent.

:>
*/



/* This is an automated file. Do not edit its contents. */


#include "rdd.h"
#include "ru_types.h"

#include "rdd_data_structures_auto.h"

/* >>>RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */
uint32_t RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1400,
	0x1400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1d00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR */
uint32_t RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1da0,
	0x1de0,
	0xa20,
	0x160,
	0x620,
	0x620,
	0x620,
	0x620,
};
/* <<<RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1dc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2a00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2a80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR */
uint32_t RDD_DS_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ac0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR */


/* >>>RDD_REGISTERS_BUFFER_ADDRESS_ARR */
uint32_t RDD_REGISTERS_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2b40,
	0x3520,
	0xe08,
	0x2740,
	0xb40,
	0xa08,
	0xa08,
	0xa08,
};
/* <<<RDD_REGISTERS_BUFFER_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2be2,
	0x2bb4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2be4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2be8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_XGPON_REPORT_TABLE_ADDRESS_ARR */
uint32_t RDD_XGPON_REPORT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2bf0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_XGPON_REPORT_TABLE_ADDRESS_ARR */


/* >>>RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */
uint32_t RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c00,
	0x2c00,
	0x2000,
	0x2400,
	0xc00,
	0xc00,
	0xc00,
	0xc00,
};
/* <<<RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */


/* >>>RDD_NATC_TBL_CFG_ADDRESS_ARR */
uint32_t RDD_NATC_TBL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e00,
	0x3700,
	0xf00,
	0x2900,
	0x2800,
	0xb00,
	0xb00,
	0xb00,
};
/* <<<RDD_NATC_TBL_CFG_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e30,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e3c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e3e,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */


/* >>>RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e3f,
	0x33f5,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e40,
	0x3740,
	INVALID_TABLE_ADDRESS,
	0x2b40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e60,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */


/* >>>RDD_TASK_IDX_ADDRESS_ARR */
uint32_t RDD_TASK_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e74,
	0x3374,
	0xfbc,
	0x29e4,
	0xadc,
	0xb7c,
	0xb7c,
	0xb7c,
};
/* <<<RDD_TASK_IDX_ADDRESS_ARR */


/* >>>RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */
uint32_t RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e78,
	0x3378,
	0xa08,
	0xe08,
	0x608,
	0x608,
	0x608,
	0x608,
};
/* <<<RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e94,
	0x33f6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */
uint32_t RDD_SRAM_DUMMY_STORE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e96,
	0x35bc,
	0xfe7,
	0x2a3f,
	0xaef,
	0xbef,
	0xbef,
	0xbef,
};
/* <<<RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR */
uint32_t RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e97,
	0x35bd,
	0x23e4,
	0x2ae2,
	0x21bd,
	0xbf2,
	0xbf2,
	0xbf2,
};
/* <<<RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR */


/* >>>RDD_MIRRORING_SCRATCH_ADDRESS_ARR */
uint32_t RDD_MIRRORING_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e98,
	0x35e8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_MIRRORING_SCRATCH_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ea0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */


/* >>>RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2eb4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2eb5,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2eb8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ec0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ed8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ee0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ef0,
	0x36f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_FPM_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2f00,
	0x3730,
	0x2770,
	0x2a70,
	0x21f0,
	0xb70,
	0xb70,
	0xb70,
};
/* <<<RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR */
uint32_t RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2f10,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x3000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x3800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR */
uint32_t RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1d00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1dd8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2b00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2b90,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ba0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */


/* >>>RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2bb6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EPON_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EPON_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2bb8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EPON_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2bc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_SSID_MAC_ADDRESS_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_SSID_MAC_ADDRESS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_SSID_MAC_ADDRESS_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DHD_STATION_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DHD_STATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DHD_STATION_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3200,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DFT_LIST_ENTRY_SCRATCH_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DFT_LIST_ENTRY_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x32c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DFT_LIST_ENTRY_SCRATCH_ADDRESS_ARR */


/* >>>RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3300,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3360,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_DHD_L2_HEADER_ADDRESS_ARR */
uint32_t RDD_DHD_L2_HEADER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3380,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_L2_HEADER_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x33c8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x21b0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR */
uint32_t RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x33d0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x33e0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x33f4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DFT_ADDR_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DFT_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x33f8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DFT_ADDR_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR */
uint32_t RDD_US_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x34a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x35a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x35b0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_FIFO_SIZE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_FIFO_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x35be,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_FIFO_SIZE_ADDRESS_ARR */


/* >>>RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x35bf,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EPON_INGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EPON_INGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x35c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EPON_INGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x35f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DFT_LIST_SIZE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DFT_LIST_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3600,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DFT_LIST_SIZE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EPON_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EPON_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3640,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EPON_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_MCAST_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MCAST_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3670,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_MCAST_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3680,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2180,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x36b0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xbf0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_DOORBELL_VALUE_ADDRESS_ARR */


/* >>>RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x36c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3760,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_FLOW_RING_MGMT_DESCRIPTOR_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_FLOW_RING_MGMT_DESCRIPTOR_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3780,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_POST_FLOW_RING_MGMT_DESCRIPTOR_BUFFER_ADDRESS_ARR */


/* >>>RDD_EPON_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_EPON_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x37c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EPON_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DHD_STATION_CTX_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DHD_STATION_CTX_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DHD_STATION_CTX_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3840,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_MCAST_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MCAST_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3880,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_MCAST_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_MCAST_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MCAST_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x38c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_MCAST_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_HW_CFG_ADDRESS_ARR */
uint32_t RDD_DHD_HW_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3900,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2780,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_HW_CFG_ADDRESS_ARR */


/* >>>RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_RX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_RX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x400,
	0x800,
	0x0,
	0x0,
	0x0,
	0x0,
};
/* <<<RDD_RX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_LAYER2_HEADER_COPY_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_LAYER2_HEADER_COPY_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x680,
	0xa80,
	0x280,
	0x280,
	0x280,
	0x280,
};
/* <<<RDD_LAYER2_HEADER_COPY_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x6f8,
	0xaf8,
	0x2f8,
	0x2f8,
	0x2f8,
	0x2f8,
};
/* <<<RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR */


/* >>>RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR */
uint32_t RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x700,
	0xb00,
	0x300,
	0x300,
	0x300,
	0x300,
};
/* <<<RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR */


/* >>>RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x800,
	0xc00,
	0x400,
	0x400,
	0x400,
	0x400,
};
/* <<<RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa10,
	0xe10,
	0x610,
	0x610,
	0x610,
	0x610,
};
/* <<<RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */
uint32_t RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa40,
	0x3c0,
	0x640,
	0x640,
	0x640,
	0x640,
};
/* <<<RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */


/* >>>RDD_POLICER_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_POLICER_PARAMS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa80,
	0x2280,
	0xa80,
	0x680,
	0x680,
	0x680,
};
/* <<<RDD_POLICER_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xad0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xae0,
	0xe20,
	0x6e0,
	0x6e0,
	0x6e0,
	0x6e0,
};
/* <<<RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xb00,
	0x2300,
	0x700,
	0x700,
	0x700,
	0x700,
};
/* <<<RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR */


/* >>>RDD_PBIT_TO_GEM_TABLE_ADDRESS_ARR */
uint32_t RDD_PBIT_TO_GEM_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xb80,
	0xe40,
	0xa40,
	0x780,
	0x780,
	0x780,
};
/* <<<RDD_PBIT_TO_GEM_TABLE_ADDRESS_ARR */


/* >>>RDD_DUAL_STACK_LITE_TABLE_ADDRESS_ARR */
uint32_t RDD_DUAL_STACK_LITE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xbc0,
	0xfc0,
	0xb00,
	0x7c0,
	0x7c0,
	0x7c0,
};
/* <<<RDD_DUAL_STACK_LITE_TABLE_ADDRESS_ARR */


/* >>>RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xc00,
	0x2000,
	0x800,
	0x800,
	0x800,
	0x800,
};
/* <<<RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_PROCESSING_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */
uint32_t RDD_PROCESSING_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe88,
	0xef8,
	0xa08,
	0xa88,
	0xa88,
	0xa88,
};
/* <<<RDD_PROCESSING_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_REPLY_ADDRESS_ARR */
uint32_t RDD_FPM_REPLY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe90,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_FPM_REPLY_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xea0,
	0x2940,
	0x2360,
	0xaa0,
	0xaa0,
	0xaa0,
};
/* <<<RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf30,
	0xf90,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf40,
	0x27c0,
	0xfc0,
	0xb40,
	0xb40,
	0xb40,
};
/* <<<RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf68,
	0x2208,
	0xa38,
	0xa90,
	0xa90,
	0xa90,
};
/* <<<RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf70,
	0x22f0,
	0xa10,
	0x6d0,
	0x6d0,
	0x6d0,
};
/* <<<RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_CFG_EX_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_CFG_EX_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf80,
	0x2a00,
	0x2580,
	0xb80,
	0xb80,
	0xb80,
};
/* <<<RDD_VPORT_CFG_EX_TABLE_ADDRESS_ARR */


/* >>>RDD_NULL_BUFFER_ADDRESS_ARR */
uint32_t RDD_NULL_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfa8,
	0x2238,
	0xfe8,
	0xa98,
	0xa98,
	0xa98,
};
/* <<<RDD_NULL_BUFFER_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfb0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */
uint32_t RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */


/* >>>RDD_FORCE_IC_IP_FLOW_ADDRESS_ARR */
uint32_t RDD_FORCE_IC_IP_FLOW_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfe4,
	0x29e3,
	0xaec,
	0xb6d,
	0xb6d,
	0xb6d,
};
/* <<<RDD_FORCE_IC_IP_FLOW_ADDRESS_ARR */


/* >>>RDD_FORCE_DSCP_ADDRESS_ARR */
uint32_t RDD_FORCE_DSCP_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfe5,
	0x2a3d,
	0xaed,
	0xb6e,
	0xb6e,
	0xb6e,
};
/* <<<RDD_FORCE_DSCP_ADDRESS_ARR */


/* >>>RDD_CORE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_CORE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfe6,
	0x2a3e,
	0xaee,
	0xb6f,
	0xb6f,
	0xb6f,
};
/* <<<RDD_CORE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfe8,
	0x27e8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xff0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_LOW_THRESHOLD_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_LOW_THRESHOLD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xffc,
	0x2a66,
	0xafc,
	0xbe2,
	0xbe2,
	0xbe2,
};
/* <<<RDD_DHD_FPM_LOW_THRESHOLD_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_HIGH_THRESHOLD_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_HIGH_THRESHOLD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xffe,
	0x2a7c,
	0xafe,
	0xbe4,
	0xbe4,
	0xbe4,
};
/* <<<RDD_DHD_FPM_HIGH_THRESHOLD_ADDRESS_ARR */


/* >>>RDD_DS_PACKET_BUFFER_ADDRESS_ARR */
uint32_t RDD_DS_PACKET_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1000,
	0x1000,
	0x1000,
	0x1000,
	0x1000,
	0x1000,
};
/* <<<RDD_DS_PACKET_BUFFER_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2200,
	0x200,
	0xe00,
	0xe00,
	0xe00,
	0xe00,
};
/* <<<RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR */


/* >>>RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23c0,
	0x29c0,
	0x21c0,
	0xbc0,
	0xbc0,
	0xbc0,
};
/* <<<RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23e2,
	0x2a7e,
	0x21e2,
	0xbe6,
	0xbe6,
	0xbe6,
};
/* <<<RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_INGRESS_QOS_DONT_DROP_RATIO_ADDRESS_ARR */
uint32_t RDD_INGRESS_QOS_DONT_DROP_RATIO_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23e5,
	0x2ae3,
	0x21e4,
	0xbf3,
	0xbf3,
	0xbf3,
};
/* <<<RDD_INGRESS_QOS_DONT_DROP_RATIO_ADDRESS_ARR */


/* >>>RDD_INGRESS_QOS_WAN_UNTAGGED_PRIORITY_ADDRESS_ARR */
uint32_t RDD_INGRESS_QOS_WAN_UNTAGGED_PRIORITY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23e6,
	0x2ae4,
	0x21e5,
	0xbf4,
	0xbf4,
	0xbf4,
};
/* <<<RDD_INGRESS_QOS_WAN_UNTAGGED_PRIORITY_ADDRESS_ARR */


/* >>>RDD_IC_DEBUG_COUNTER_MODE_ADDRESS_ARR */
uint32_t RDD_IC_DEBUG_COUNTER_MODE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23e7,
	0x2ae6,
	0x21e6,
	0xbf5,
	0xbf5,
	0xbf5,
};
/* <<<RDD_IC_DEBUG_COUNTER_MODE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23e8,
	0x29e8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23f0,
	0x2930,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR */
uint32_t RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2400,
	0x600,
	0x2000,
	0x2000,
	0x2000,
	0x2000,
};
/* <<<RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR */


/* >>>RDD_RULE_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_RULE_BASED_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2580,
	0x2a40,
	0x23c0,
	0xfc0,
	0xfc0,
	0xfc0,
};
/* <<<RDD_RULE_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_IC_MCAST_ENABLE_ADDRESS_ARR */
uint32_t RDD_IC_MCAST_ENABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x25a2,
	0x2ae7,
	0x21e7,
	0xbf6,
	0xbf6,
	0xbf6,
};
/* <<<RDD_IC_MCAST_ENABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REDIRECT_MODE_ADDRESS_ARR */
uint32_t RDD_CPU_REDIRECT_MODE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x25a3,
	0x2af7,
	0x21fc,
	0xbf7,
	0xbf7,
	0xbf7,
};
/* <<<RDD_CPU_REDIRECT_MODE_ADDRESS_ARR */


/* >>>RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x25a4,
	0x2af9,
	0x21fd,
	0xbf8,
	0xbf8,
	0xbf8,
};
/* <<<RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x25a5,
	0x2afa,
	0x21fe,
	0xbf9,
	0xbf9,
	0xbf9,
};
/* <<<RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x25a8,
	0x29a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */


/* >>>RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x25b8,
	0x2a38,
	0x21b8,
	0xb68,
	0xb68,
	0xb68,
};
/* <<<RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_IPTV_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x25c0,
	0x2ac0,
	0x2540,
	0x2180,
	0x2180,
	0x2180,
};
/* <<<RDD_IPTV_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x25e8,
	0x2a68,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x25f0,
	0x29f0,
	0xff0,
	0xb30,
	0xb30,
	0xb30,
};
/* <<<RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_TX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2600,
	0x0,
	0x2400,
	0x2200,
	0x2200,
	0x2200,
};
/* <<<RDD_TX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2740,
	0x2b00,
	0x25c0,
	0x21c0,
	0x21c0,
	0x21c0,
};
/* <<<RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR */
uint32_t RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2768,
	0x2ab0,
	0x21e8,
	0xba8,
	0xba8,
	0xba8,
};
/* <<<RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2780,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_HANDLER_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_HANDLER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27a0,
	0xfa0,
	0x7e0,
	0x2340,
	0x2340,
	0x2340,
};
/* <<<RDD_TCAM_IC_HANDLER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_BRIDGE_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_BRIDGE_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27e0,
	0x2220,
	0xa20,
	0x2360,
	0x2360,
	0x2360,
};
/* <<<RDD_BRIDGE_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27f8,
	0x2ab8,
	0x2350,
	0xbb0,
	0xbb0,
	0xbb0,
};
/* <<<RDD_IPTV_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2800,
	0x2600,
	0x2600,
	0x2400,
	0x2400,
	0x2400,
};
/* <<<RDD_VPORT_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2940,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR */
uint32_t RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2960,
	0x2ae8,
	0x2358,
	0xbb8,
	0xbb8,
	0xbb8,
};
/* <<<RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR */


/* >>>RDD_NAT_CACHE_CFG_ADDRESS_ARR */
uint32_t RDD_NAT_CACHE_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2968,
	0x2af0,
	0x23e8,
	0xbe8,
	0xbe8,
	0xbe8,
};
/* <<<RDD_NAT_CACHE_CFG_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_CFG_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2970,
	0x2b28,
	0x23f0,
	0xbf0,
	0xbf0,
	0xbf0,
};
/* <<<RDD_INGRESS_FILTER_CFG_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2980,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a00,
	0x2800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b00,
	0x2d00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b80,
	0x2d80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c00,
	0x2e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x140,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x180,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x780,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2210,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2240,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_SCRATCH_ADDRESS_ARR */
uint32_t RDD_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22d0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2380,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27fc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29b0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_WAN_VIQ_EXCLUSIVE_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_WAN_VIQ_EXCLUSIVE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29e2,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_WAN_VIQ_EXCLUSIVE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a28,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a62,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a64,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR */


/* >>>RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2aa8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_MAC_TYPE_ADDRESS_ARR */
uint32_t RDD_MAC_TYPE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ae5,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_MAC_TYPE_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2af8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_TO_TC_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_TO_TC_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2be0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_TO_TC_ADDRESS_ARR */


/* >>>RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_TC_TO_CPU_RXQ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c20,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c60,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2cc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */


/* >>>RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x680,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x780,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xad0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xae0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xaf0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xbc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xbfc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xbfe,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x21be,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR */
uint32_t RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2200,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_REPLY_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_REPLY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2740,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FPM_REPLY_ADDRESS_ARR */

