#ifndef RUNNER_C_CODE_ADDRESSES
#define RUNNER_C_CODE_ADDRESSES

#define runner_c_start_task_initialization_task		(0x14)
#define runner_c_initialization_task		(0x14)
#define runner_c_start_task_timer_scheduler_set		(0xEEC)
#define runner_c_timer_scheduler_set		(0xEEC)
#define runner_c_start_task_eth_tx_scheduling_wakeup_request		(0xA40)
#define runner_c_eth_tx_scheduling_wakeup_request		(0xA40)
#define runner_c_start_task_eth_tx_wakeup_request		(0xA88)
#define runner_c_eth_tx_wakeup_request		(0xA88)
#define runner_c_start_task_cpu_tx_wakeup_request		(0x103C)
#define runner_c_cpu_tx_wakeup_request		(0x103C)
#define runner_c_start_task_lan_enqueue_runner_A_wakeup_request		(0x18C)
#define runner_c_lan_enqueue_runner_A_wakeup_request		(0x18C)
#define runner_c_start_task_lan_enqueue_runner_B_wakeup_request		(0x1A0)
#define runner_c_lan_enqueue_runner_B_wakeup_request		(0x1A0)
#define runner_c_start_task_lan_enqueue_ds_wakeup_request		(0x570)
#define runner_c_lan_enqueue_ds_wakeup_request		(0x570)
#define runner_c_start_task_debug_routine		(0xA4)
#define runner_c_debug_routine		(0xA4)
#define runner_c_start_task_service_queue_enqueue_wakeup_request		(0x464)
#define runner_c_service_queue_enqueue_wakeup_request		(0x464)
#define runner_c_start_task_cpu_rx_int_coalesce_timer_1st_wakeup_request		(0x1DD8)
#define runner_c_cpu_rx_int_coalesce_timer_1st_wakeup_request		(0x1DD8)
#define runner_c_start_task_wlan_mcast_wakeup_request		(0x1EAC)
#define runner_c_wlan_mcast_wakeup_request		(0x1EAC)
#define runner_c_ds_rate_limiter_budget_allocate_loop		(0xF64)
#define runner_c_ds_service_queue_rate_limiter_budget_allocate		(0x1028)

#endif
