#!/bin/sh

case "$1" in
	start)
		# if you want to customize the trace feature, copy this file to 
		# trace.sh.custom and do your customization there.  Do not edit this file.
		# Below are some useful customizations:
		# increase trace buffer size to 2MB
		# echo 2048 > /sys/kernel/debug/tracing/buffer_size_kb
		# use high resolution clock instead of 1ms ticks
		# echo global-clock > /sys/kernel/debug/tracing/trace_options
		exit 0
		;;

	stop)
		echo "stop trace not implemented"
		exit 1
		;;

	*)
		echo "$0: unrecognized option $1"
		exit 1
		;;

esac

