#ifndef RUNNER_B_CODE_ADDRESSES
#define RUNNER_B_CODE_ADDRESSES

#define runner_b_start_task_initialization_task		(0x14)
#define runner_b_initialization_task		(0x14)
#define runner_b_start_task_timer_scheduler_set		(0x2434)
#define runner_b_timer_scheduler_set		(0x2434)
#define runner_b_start_task_cpu_rx_wakeup_request		(0xD58)
#define runner_b_cpu_rx_wakeup_request		(0xD58)
#define runner_b_start_task_cpu_tx_wakeup_request		(0x1D5C)
#define runner_b_cpu_tx_wakeup_request		(0x1D5C)
#define runner_b_start_task_policer_budget_allocator_1st_wakeup_request		(0x2830)
#define runner_b_policer_budget_allocator_1st_wakeup_request		(0x2830)
#define runner_b_start_task_rate_control_budget_allocator_1st_wakeup_request		(0x1C3C)
#define runner_b_rate_control_budget_allocator_1st_wakeup_request		(0x1C3C)
#define runner_b_start_task_wan_interworking_enqueue_wakeup_request		(0x174)
#define runner_b_wan_interworking_enqueue_wakeup_request		(0x174)
#define runner_b_start_task_wan_tx_wakeup_request		(0x5E4)
#define runner_b_wan_tx_wakeup_request		(0x5E4)
#define runner_b_start_task_debug_routine		(0x8C)
#define runner_b_debug_routine		(0x8C)
#define runner_b_start_task_spdsvc_timer_1st_wakeup_request		(0x2394)
#define runner_b_spdsvc_timer_1st_wakeup_request		(0x2394)
#define runner_b_start_task_free_skb_index_wakeup_request		(0x25C8)
#define runner_b_free_skb_index_wakeup_request		(0x25C8)
#define runner_b_start_task_dhd_tx_post		(0x298C)
#define runner_b_dhd_tx_post		(0x298C)
#define runner_b_cpu_rx_meter_budget_allocate		(0x24B4)
#define runner_b_upstream_rate_limiter_budget_allocate		(0x2500)
#define runner_b_schedule_free_skb_index		(0x25AC)

#endif
