#ifndef RUNNER_C_CODE_ADDRESSES
#define RUNNER_C_CODE_ADDRESSES

#define runner_c_start_task_initialization_task		(0x14)
#define runner_c_initialization_task		(0x14)
#define runner_c_start_task_timer_scheduler_set		(0x854)
#define runner_c_timer_scheduler_set		(0x854)
#define runner_c_start_task_lan_tx_wakeup_request		(0x450)
#define runner_c_lan_tx_wakeup_request		(0x450)
#define runner_c_start_task_cpu_tx_wakeup_request		(0xAE0)
#define runner_c_cpu_tx_wakeup_request		(0xAE0)
#define runner_c_start_task_lan_enqueue_ih_wakeup_request		(0x1C4)
#define runner_c_lan_enqueue_ih_wakeup_request		(0x1C4)
#define runner_c_start_task_lan_enqueue_pd_wakeup_request		(0x208)
#define runner_c_lan_enqueue_pd_wakeup_request		(0x208)
#define runner_c_start_task_multicast_lan_enqueue_wakeup_request		(0x258)
#define runner_c_multicast_lan_enqueue_wakeup_request		(0x258)
#define runner_c_start_task_wlan_mcast_wakeup_request		(0x2DD4)
#define runner_c_wlan_mcast_wakeup_request		(0x2DD4)
#define runner_c_start_task_cpu_rx_int_coalesce_timer_1st_wakeup_request		(0xA28)
#define runner_c_cpu_rx_int_coalesce_timer_1st_wakeup_request		(0xA28)
#define runner_c_start_task_debug_routine		(0xDC)
#define runner_c_debug_routine		(0xDC)
#define runner_c_start_task_gso_wakeup_request		(0x1CC4)
#define runner_c_gso_wakeup_request		(0x1CC4)
#define runner_c_start_task_spdsvc_timer_1st_wakeup_request		(0x1000)
#define runner_c_spdsvc_timer_1st_wakeup_request		(0x1000)
#define runner_c_start_task_free_skb_index_wakeup_request		(0x9C4)
#define runner_c_free_skb_index_wakeup_request		(0x9C4)
#define runner_c_start_task_service_queue_dequeue_wakeup_request		(0x36F0)
#define runner_c_service_queue_dequeue_wakeup_request		(0x36F0)
#define runner_c_start_task_service_queue_enqueue_wakeup_request		(0x37C0)
#define runner_c_service_queue_enqueue_wakeup_request		(0x37C0)
#define runner_c_ds_rate_limiter_budget_allocate		(0x8D4)
#define runner_c_ds_service_queue_rate_limiter_budget_allocate		(0x990)
#define runner_c_schedule_free_skb_index		(0x9A8)

#endif
