/****************************************************************
* $Id: mocad_strings.h 11910 2009-11-19 13:51:35Z amirm $
*
* Project:      MoCA Core
*
* Description:  Strings IDs for the host driver
*
* Copyright:    (c) Broadcom 2007 , Confidential and Proprietary
******************************************************************/

#ifndef __MOCAD_STRINGS_H__
#define __MOCAD_STRINGS_H__

/* Generated from SVN - the SVN version string */
#define MOCAD_STRINGS_VER_STRING "$Rev: 24124 $"

#define MOCA_2_HOST_STR_ID(layer, id)  (((layer) << 16) | (id))
#define GET_MOCA_LAYER_ID(stringID)    ((stringID) >> 16)
#define GET_MOCA_STRING_ID(stringID)   ((stringID) & 0xFFFF)

#define MAX_STRING_LENGTH              250

#ifndef MIN
#define MIN(a, b)                      (((a) < (b)) ? (a) : (b))
#endif

typedef enum 
{
   MOCA_GENERAL_STR_LAYER = 0,
   MOCA_MLME_STR_LAYER,
   MOCA_HOST_MMP_LAYER,
   MOCA_PHY_STR_LAYER,
   MOCA_MAC_STR_LAYER,
   MOCA_DME_STR_LAYER,
   MOCA_ECL_STR_LAYER,
   MOCA_QM_STR_LAYER,
   MOCA_L2_STR_LAYER,
   MOCA_STR_LAYER_LAST,
} MocaCoreLayersStrings_E;

typedef struct
{
   char **string_array;
   unsigned int string_array_size;
} StringsArray_T;

#endif /* __MOCAD_STRINGS_H__ */

#ifdef STRING_DECL
char *moca_core_lab_GENERAL_strings[] = {
   /*00*/   "\nChange link state %d -> %d\n"                                                                            ,
   /*01*/   "Node ID %d was not found in the Best score nodes table\n"                                                  ,
   /*02*/   "nid:              0x%X\n"                                  , 
   /*03*/   "NC ID:            0x%X (Broadcom)\n"                                                                       ,
   /*04*/   "NC ID:            0x%X (non-Broadcom)\n"                                                                   ,
   /*05*/   "NC ID:            0x%X\n"                                                                                  ,
   /*06*/   "ANB:              0x%X\n"                                                                                  ,
   /*07*/   "Pending4Remove:   0x%X\n"                                                                                  ,
   /*08*/   "BRCM NB:          0x%X\n"                                                                                  ,
   /*09*/   "1.0 NB:           0x%X\n"                                                                                  ,
   /*10*/   "1.1 ProTemNB:     0x%x\n"                                                                                  ,
   /*11*/   "Backup NC ID:     0x%x\n"                                                                                  ,
   /*12*/   "MoCA version:     0x%x\n"                                                                                  ,
   /*13*/   "BH Mode:          0x%x\n"                                                                                  ,
   /*14*/   "Node in adm:      0x%X\n"                                                                                  ,
   /*15*/   "Link state:       0x%X\n"                                                                                  ,
   /*16*/   "L2 Task started\n"                                                                                         ,
   /*17*/   "Trace locked (%d)\n"                                                                                       ,
   /*18*/   "RTT is unlocked\n"                                                                                         ,
   /*19*/   "RTT is locked\n"                                                                                           ,
   /*20*/   "Trace unlocked\n"                                                                                          ,
   /*21*/   "Set link state [Req|00|To|From] %08X\n"                                                                    ,
   /*22*/   "Delaying LS change due to remove-nodes (requested %X)\n"                                                   ,
   /*23*/   "Warning: Partial set of link state\n"                                                                      ,
   /*24*/   "\nNC node ID changed to %d\n"                                                                              ,
   /*25*/   "\nNC node ID changed to UNKNOWN\n"                                                                         ,
   /*26*/   "\nChange BH mode: %08X\n"                                                                                  ,
   /*27*/   "Start resync\n"                                                                                            ,
   /*28*/   "Too many pkts\n"                                                                                           ,
   /*29*/   "Error OS timer\n"                                                                                          ,
   /*30*/   "BBS task started!\n"                                                                                       ,
   /*31*/   "Temp%x: 0x%x\n"                                                                                            ,
   /*32*/   "Temp%x: 0x%x 0x%x\n"                                                                                       ,
   /*33*/   "Temp%x: 0x%x 0x%x 0x%x\n"                                                                                  ,
   /*34*/   "Temp%x: 0x%x 0x%x 0x%x 0x%x\n"                                                                             ,
   /*35*/   "Error: %d\n"                                                                                               ,
   /*36*/   "\nTM_diff=%d, TM_diffAv=%d, TM_diffMax=%d, TM_Period=%d\n"                                                 ,
   /*37*/   "Error - Unknown L2 msg type (%x)\n"                                                                        ,
   /*38*/   "BestSCore: Index=%d -- %x %x %x %x %x %x %x %x\n"                                                          ,
   /*39*/   "BestSCore: Index=%d -- %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x\n"                                  ,
   /*40*/   "Error %d:   %d\n"                                                                                          ,
   /*41*/   "Error %d:   %d   %d\n"                                                                                     ,
   /*42*/   "Error %d:   %d   %d   %d\n"                                                                                ,
   /*43*/   "ANB: Add node [to <- from]: 0x%08X (node ID: 0x%X)\n"                                                      ,
   /*44*/   "LL=%lld \n"                                                                                                ,
   /*45*/   "ULL=%llu \n"                                                                                               ,
   /*46*/   "DebugPrintArray: %08x %08x\n"                                                                              ,
   /*47*/   "Temp:   %d\n"                                                                                              ,
   /*48*/   "Temp%d: %d\n"                                                                                              ,
   /*49*/   "Temp%d: %d %d\n"                                                                                           ,
   /*50*/   "Temp%d: %d %d %d\n"                                                                                        ,
   /*51*/   "Temp%d: %d %d %d %d\n"                                                                                     ,
   /*52*/   "ISR stack used: %d [words]\n"                                                                              ,
   /*53*/   "Left Heap size: %d [bytes]\n"                                                                              ,
   /*54*/   "Toggle GPIO %d\n"                                                                                          ,
   /*55*/   "Send to host reset-request trap\n"                                                                         ,
   /*56*/   "RTT buffer size %d [words]\n"                                                                              ,
};

char *moca_core_lab_DME_strings[] = {
   /*00*/   "Adm failed\n"                                                                                              ,
   /*01*/   "Adm abort: ANB=0x%X, NnID=%d, LS=%X\n"                                                                     ,
   /*02*/   "LMO failed on node %d\n"                                                                                   ,
   /*03*/   "LMO_RemoveProfiles\n"                                                                                      ,
   /*04*/   "LMO_RemoveProfiles doing..\n"                                                                              ,
   /*05*/   "Start OOO LMO (node: %d)\n"                                                                                ,
   /*06*/   "DP-%d\n"                                                                                                   ,
   /*07*/   "Periodic Task started\n"                                                                                   ,
   /*08*/   "P_QR\n"                                                                                                    ,
   /*09*/   "#"                                                                                                         ,
   /*10*/   "*"                                                                                                         ,
   /*11*/   "\nPPS rate: Ingress %d - Egress %d\n"                                                                      ,
   /*12*/   "=====================================================\n"                                                   ,
   /*13*/   "\n"                                                                                                        ,
   /*14*/   "DME_RemoveAllExistingNodes. ANB = 0x%X\n"                                                                  ,
   /*15*/   "DME Remove node %d\n"                                                                                      ,
   /*16*/   "  RN: Receive complete ind. (%d)\n"                                                                        ,
   /*17*/   "Admission Timer (T2) expired\n"                                                                            ,
   /*18*/   "."                                                                                                         ,
   /*19*/   "Not receiving beacons. Giving up on channel.\n"                                                            ,
   /*20*/   "Not receiving AdmReq opportunities. Giving up on channel.\n"                                               ,
   /*21*/   "Privacy mismatch, network full or in NC black list. Giving up on channel.\n"                               ,
   /*22*/   "Not receiving beacons. Giving up on channel.\n"                                                            ,
   /*23*/   "Setting RF channel to %d\n"                                                                                ,
   /*24*/   "Drop adm req - reason 0x%x 0x%x\n"                                                                         ,
   /*25*/   "No available node ID - 0x%x\n"                                                                             ,
   /*26*/   "Drop adm req - reason 0x%x 0x%x (node is black listed)\n"                                                  ,
   /*27*/   "Channel %d <--> %d unusable\n"                                                                             ,
   /*28*/   "Successfully finished admission on node %d !!\n"                                                           ,
   /*29*/   "NN search for Beacons... Waiting %d ms\n"                                                                  ,
   /*30*/   "Become NC\n"                                                                                               ,
   /*31*/   "Starting Network Search... (turboEn=%d)\n"                                                                 ,
   /*32*/   "Connection established at %d MHz (LOF is %d MHz, g_RfChannel is %d)\n"                                     ,
   /*33*/   "New RF Channel: %d MHz\n"                                                                                  ,
   /*34*/   "IgnoreList: cleared\n"                                                                                     ,
   /*35*/   "IgnoreList: NN=%02X:%02X:%02X:%02X:%02X:%02X failed %d (%d)\n"                                             ,
   /*36*/   "Black List Debugging: Node failed adm for the %d time\n"                                                   ,
   /*37*/   "IgnoreList: full\n"                                                                                        ,
   /*38*/   "EN ADM Abort indication\n"                                                                                 ,
   /*39*/   "LMO: Prim-%02d, data-%08x, Event-%d, LS - %d, LN - %d\n"                                                   ,
   /*40*/   ">\n\n"                                                                                                     ,
   /*41*/   "ADM: Prim-%d\n"                                                                                            ,
   /*42*/   "LMO primitive queue flush\n"                                                                               ,
   /*43*/   "Request OOO LMO to node %d\n"                                                                              ,
   /*44*/   "\nPNS I --> PNS II\n"                                                                                      ,
   /*45*/   "Setting PNS timer to %d ms\n"                                                                              ,
   /*46*/   "NS - Beacon arrived!\n"                                                                                    ,
   /*47*/   "\nNS - Timeout waiting for beacons\n"                                                                      ,
   /*48*/   "Setting seed to 0x%x\n"                                                                                    ,
   /*49*/   "\nGot Taboo mask from NN 0x%x\n"                                                                           ,
   /*50*/   "\nGot Taboo start from NN %d\n"                                                                            ,
   /*51*/   "\nOld Taboo: Start Channel: %d Channel Mask: 0x%x\n"                                                       ,
   /*52*/   "\nNew Taboo: Start Channel: %d Channel Mask: 0x%x\n"                                                       ,
   /*53*/   "\nADM_TaskMainFunc\n"                                                                                      ,
   /*54*/   "\nADM_FindChannel\n"                                                                                       ,
   /*55*/   "MoCA Link Up\n"                                                                                            ,
   /*56*/   "\nBEACON_ParseBeacon\n"                                                                                    ,
   /*57*/   "\nMLME_SendAdmissionRequest\n"                                                                             ,
   /*58*/   "\nMLME_HandleControlFrame\n"                                                                               ,
   /*59*/   "Host fixed mask start: %x, Host fixed channel mask : %x, Taboo derived from RF type %x\n"                  ,
   /*60*/   "NC search for NN ... Waiting %d ms\n"                                                                      ,
   /*61*/   "\nNS - Timeout waiting for admission request\n"                                                            ,
   /*62*/   "Task - %c%c%c, Prio %d, Stack Depth %d, Overflow=%d\n"                                                     ,
   /*63*/   "Start NS as IRD after channel selection. Tx beacons for %d sec\n"                                          ,
   /*64*/   "Start NS not after MR\n"                                                                                   ,
   /*65*/   "NS params - BC      =%4d, lof    =%4d\nNS params - RF type=%4d, SingleCh=%4d, NC Mode=%4d\n"               ,
   /*66*/   "Setting init BC to %d\n"                                                                                   ,
   /*67*/   "Setting init BC-Set to %d\n"                                                                               ,
   /*68*/   "Turn Preliminary NS off (NC mod=%d, NS=%d)\n"                                                              ,
   /*69*/   "\nPNS timer had expired!\n"                                                                                ,
   /*70*/   "\nMR  timer had expired!\n"                                                                                ,
   /*71*/   "\nQM ISR max timings: Max QM duration=%d[uSec], max duration between QM ISRs=%d[uSec]\n"                   ,
   /*72*/   "\nQM ISR average timings: Duration: %d[uS], Duration between ISRs=%d[uS]\n"                                ,
   /*73*/   "My only channel is Taboo!\n"                                                                               ,
   /*74*/   "ADM: Prim-%02d, data-%08x, Event-%d, LS - %d, NN - %d\n"                                                   ,
   /*75*/   "Got Taboo:"                                                                                                ,
   /*76*/   "My  Taboo:"                                                                                                ,
   /*77*/   "Channel %d is taboo!\n"                                                                                    ,
   /*78*/   "Channel %d is not taboo!\n"                                                                                ,
   /*79*/   "New Taboo:"                                                                                                ,
   /*80*/   " %d"                                                                                                       ,
   /*81*/   " %x\n"                                                                                                     ,
   /*82*/   "MoCA Link Down\n"                                                                                          ,
   /*83*/   "\nPulling TimeOut - ID=%d, TO=%d\n"                                                                        ,
};

char *moca_core_lab_HOST_MMP_strings[] = {
   /*00*/   "RX Power(dBM)   Margin(DB)\n"                                                                              ,
   /*01*/   "(%x)     %x             %x \n"                                                                             ,
   /*02*/   "g_sigma2IndB[%d] = %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d \n"                                     ,
   /*03*/   "INIT Configurations (HEX):\n"                                                                              ,
   /*04*/   "%08x %08x %08x %08x %08x %08x %08x %08x\n"                                                                 ,
   /*05*/   "ContPwrTxMode On"                                                                                          ,
   /*06*/   "RxMode On"                                                                                                 ,
   /*07*/   "Change threshold for triggering OOO LMO %d -> %d\n"                                                        ,
};

char *moca_core_lab_ECL_strings[] = {
   /*00*/   "Qage:%08x\n"                                                                                               ,
   /*01*/   "FC ON  %x\n"                                                                                               ,
   /*02*/   "FC OFF %x\n"                                                                                               ,
   /*03*/   "FC STT %x\n",
};

char *moca_core_lab_MLME_strings[] = {
   /*00*/   "Fail enqueue LC. Subtype=%x, dest=%x\n"                                                                             ,
   /*01*/   "Set IQ Diagram parameters: NodeId-%d, BurstType-%d, AcmtSymNum-%d\n"                                                ,
   /*02*/   "MLME Halt!\n\n"                                                                                                     ,
   /*03*/   "Tx Probe Report: Unusable channel to node %d (PhyPrf=%x)\n"                                                         ,
   /*04*/   "Tx Report II: numSym=%d,cp=%d,#Pkts=%d,sc1=%d,sc2=%d,Status=%d\n"                                                   ,
   /*05*/   "Tx AdmRes: maxTpcAdj=%d, NnId=%d, NN_MAC=%02X:%02X:%02X:%02X:%02X:%02X, NC_MAC=%02X:%02X:%02X:%02X:%02X:%02X\n"     ,
   /*06*/   "\n+===========================================================================\n"                                   ,
   /*07*/   "-===========================================================================\n"                                     ,
   /*08*/   "@ LMO : LNId=%x, MyID=%x, NcID=%x, BkNc(prev)=%x, LMO_Cnt=%d\n"                                                     ,
   /*09*/   "@ MAC : LN=%02X:%02X:%02X:%02X:%02X:%02X, Self=%02X:%02X:%02X:%02X:%02X:%02X, NC=%02X:%02X:%02X:%02X:%02X:%02X\n"   ,
   /*10*/   "@ INF1: LOF=%d, ANB=%x, SW_Ver=%d.%d.%d, NT_Ver=%2x, NC_Md=%d, Privacy=%d\n"                                        ,
   /*11*/   "@ Rx  : nBas=%04d, cp=%02d, PR=%03d, BO=%02d, HT=%d, AGC=%02d, RS=%06d, RxCnt=%d\n"                                 ,
   /*12*/   "@ Tx  : nBas=%04d, cp=%02d, PR=%03d, BO=%02d, HT=%d,                    TxCnt=%d\n"                                 ,
   /*13*/   "@ Bc  : nBas=%04d, cp=%02d, PR=%03d, BO=%02d, AGC=%02d, PREV_AGC=%02d, RS=%06d\n"                                   ,
   /*14*/   "@ Bc  : nBas=%04d, cp=%02d, PR=%03d, BO=%02d, AGC=%02d\n"                                                           ,
   /*15*/   "@ CCOF: HT=%d, UC=%d, BC=%d, MAP=%d, MAP_P1=%d\n"                                                                   ,
   /*16*/   "@ CSFO: C_SFO_50=%06d, CFO_50=%06d, C_SFO_100=%06d, CFO_100=%06d\n"                                                 ,
   /*17*/   "@ CRC    : Node=%02d,Bcn=%02d,MAP=%02d,RR=%02d,LC=%02d,UC_Eth=%04d,BC_Eth=%04d\n"                                   ,
   /*18*/   "@ TIMEOUT: Node=%02d,Bcn=%02d,MAP=%02d,RR=%02d,LC=%02d,UC_Eth=%04d,BC_Eth=%04d,P1=%02d,P2=%02d,P3=%02d,P1g=%02d\n"  ,
   /*19*/   "@ TIMEOUT: Node=%02d,Bcn=%02d,MAP=%02d,RR=%02d,LC=%02d,UC_Eth=%04d,BC_Eth=%04d,P1=%02d,P2=%02d,P3=%02d\n"           ,
   /*20*/   "@ Bc  : nBas=%04d, cp=%02d, PR=%03d, BO=%02d, BcTxCnt=%d\n"                                                         ,
   /*21*/   "Tx AdmReq: NdPrtSp=%x, initPwr=%d, NN_MAC=%02X:%02X:%02X:%02X:%02X:%02X, MAC_CLK=%08x\n"                            ,
   /*22*/   "Tx PwrRsp: nid=%d BO %d\n"                                                                                          ,
   /*23*/   "Tx PwrAck: nid=%d maxTpcAdj=%d\n"                                                                                   ,
   /*24*/   "Removing node %d\n"                                                                                                 ,
   /*25*/   "\n\\Node %d"                                                                                                        ,
   /*26*/   " (self) "                                                                                                           ,
   /*27*/   ""                                                                                                                   ,  /* -- NOT USED -- */
   /*28*/   " removed\n"                                                                                                         ,
   /*29*/   "New node: Id=%d, MAC=%02X:%02X:%02X:%02X:%02X:%02X, MocaVer=%x, PrSprt=%8x\n"                                       ,
   /*30*/   "Starting NC Handoff from within MLME_UpdateBestScores, to NID=%d\n"                                                 ,
   /*31*/   "Node %d - BC nbas %d (self)\n"                                                                                      ,
   /*32*/   "Node %d - BC nbas %d\n"                                                                                             ,
   /*33*/   "Rx Probe report: Error channel to node %d not usable. (phyProfile=%x)\n"                                            ,
   /*34*/   "Prb rpt[0] - Unusable Channel. nbas %x\n"                                                                           ,
   /*35*/   "Prb rpt[1] - Unusable Channel. nbas %x\n"                                                                           ,
   /*36*/   "Skip probe II\n"                                                                                                    ,
   /*37*/   "Skip Probe II (CFO<5KHz)\n"                                                                                         ,
   /*38*/   "Use Probe II CFO=%d\n"                                                                                              ,
   /*39*/   "No Probe II\n"                                                                                                      ,
   /*40*/   "Rx Report II: numSym=%d,cp=%d,numOfPkts=%d,sc1=%d,sc2=%d,Status=%d\n"                                               ,
   /*41*/   "EN/NN duplicate mac (%02X:%02X:%02X:%02X:%02X:%02X) in id %d (NN %d)\n"                                             ,
   /*42*/   "Adm started on another NN (MAC=%02X:%02X:%02X:%02X:%02X:%02X)\n"                                                    ,
   /*43*/   "Starting adm as EN %d. NN_id=%d, ANB=%X\n"                                                                          ,
   /*44*/   "Starting adm as NN %d. NC_id=%d, ANB=%X\n"                                                                          ,
   /*45*/   "\n\\NC handoff aborted\n"                                                                                           ,
   /*46*/   "Rx AdmRes: NcId=%x,NnId=%d,ANB=%X,maxTpcAdj=%d,"                                                                    ,
   /*47*/   "NN=%02X:%02X:%02X:%02X:%02X:%02X,NC=%02X:%02X:%02X:%02X:%02X:%02X\n"                                                ,
   /*48*/   "Rx AdmReq: NdPrtSp=%x, initPwr=%d, NN=%02X:%02X:%02X:%02X:%02X:%02X, MAC_CLK=%08x\n"                                ,
   /*49*/   "Halt adm req %d\n"                                                                                                  ,
   /*50*/   "Rx PwrCtrl: nid=%d\n"                                                                                               ,
   /*51*/   "Rx PwrRsp: nid=%d BO=%d\n"                                                                                          ,
   /*52*/   "Rx PwrAck: nid=%d maxTpcAdj=%d\n"                                                                                   ,
   /*53*/   "@ Node %d: Unusable channel on GCD BM %x\n"                                                                         ,
   /*54*/   "12610: %d %d\n"                                                                                                     ,
   /*55*/   "update TX power %d  power %d nid %x \n\n"                                                                           ,
   /*56*/   "the addr is %d\n\n"                                                                                                 ,
   /*57*/   "Node ID %d Burst Type %d gain %d lut = %d\n\n"                                                                      ,
   /*58*/   "Bad Prim handle %d (%08x, %08x, %08x)\n"                                                                            ,
   /*59*/   "P=%d,D=%d,S=%d\n"                                                                                                   ,
   /*60*/   " Nbas=%d cp=%d CFO=%d HT=%d\n"                                                                                      ,
   /*61*/   "Starting adm as NC %d. NN_id=%d, ANB=%X\n"                                                                          ,
   /*62*/   "(MLME) Req remove nid %d\n"                                                                                         ,
   /*63*/   "  Admission ack (%d)\n"                                                                                             ,
   /*64*/   "  LMO ack (%d)\n"                                                                                                   ,
   /*65*/   "  Privacy ack (%d)\n"                                                                                               ,
   /*66*/   "  L2 ack (%d)\n"                                                                                                    ,
   /*67*/   "  Abort remove node (%d)\n"                                                                                         ,
   /*68*/   "Backup NC ID changed to %d\n"                                                                                       ,
   /*69*/   "NC ID changed to %d\n"                                                                                              ,
   /*70*/   "Start remove nodes (bitmask) 0x%x\n"                                                                                ,
   /*71*/   ""                                                                                                                   ,
   /*72*/   "\n\\Start backup NC as new NC\n"                                                                                    ,
   /*73*/   "\n\\NC handoff scheduled to node ID: %d\n"                                                                          ,
   /*74*/   "\n\\handoff completed OK\n"                                                                                         ,
   /*75*/   "Open loop complete nid=%d a=%d tg=%d rs=%d\n"                                                                       ,
   /*76*/   "Outer loop complete nid=%d a=%d tg=%d rs=%d\n"                                                                      ,
   /*77*/   "printouts dropped..."                                                                                               ,
   /*78*/   "Unusable channels bitmask (node|GCD_bitmask) 0x%x\n"                                                                ,
   /*79*/   "<<<<SetAgc n=%x\n"                                                                                                  ,
   /*80*/   "aa=%d\n"                                                                                                            ,
   /*81*/   "shift CFO %d Hz\n"                                                                                                  ,
   /*82*/   "Tx GCD Probe report To node %d:\n"                                                                                  ,
   /*83*/   "Tx Unicast Probe report To node %d:\n"                                                                              ,
   /*84*/   "Tx Probe III Probe report To node %d:\n"                                                                            ,
   /*85*/   "Tx Type I GCD Probe report To node %d:\n"                                                                           ,
   /*86*/   "Rx GCD Probe report From node %d:\n"                                                                                ,
   /*87*/   "Rx Unicast Probe report From node %d:\n"                                                                            ,
   /*88*/   "Rx Probe III Probe report From node %d:\n"                                                                          ,
   /*89*/   "Rx Type I GCD Probe report From node %d:\n"                                                                         ,
   /*90*/   "\tMap      : EN %d->EN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*91*/   "\tMap      : EN %d->NC %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*92*/   "\tMap      : EN %d->NN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*93*/   "\tMap      : EN %d->BRCST %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"       ,
   /*94*/   "\tMap      : NC %d->EN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*95*/   "\tMap      : NC %d->NC %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*96*/   "\tMap      : NC %d->NN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*97*/   "\tMap      : NC %d->BRCST %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"       ,
   /*98*/   "\tMap      : NN %d->EN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*99*/   "\tMap      : NN %d->NC %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*100*/  "\tMap      : NN %d->NN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*101*/  "\tMap      : NN %d->BRCST %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"       ,
   /*102*/  "\tUnicast  : EN %d->EN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*103*/  "\tUnicast  : EN %d->NC %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*104*/  "\tUnicast  : EN %d->NN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*105*/  "\tUnicast  : EN %d->BRCST %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"       ,
   /*106*/  "\tUnicast  : NC %d->EN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*107*/  "\tUnicast  : NC %d->NC %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*108*/  "\tUnicast  : NC %d->NN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*109*/  "\tUnicast  : NC %d->BRCST %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"       ,
   /*110*/  "\tUnicast  : NN %d->EN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*111*/  "\tUnicast  : NN %d->NC %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*112*/  "\tUnicast  : NN %d->NN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*113*/  "\tUnicast  : NN %d->BRCST %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"       ,
   /*114*/  "\tBroadcast: EN %d->EN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*115*/  "\tBroadcast: EN %d->NC %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*116*/  "\tBroadcast: EN %d->NN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*117*/  "\tBroadcast: EN %d->BRCST %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"       ,
   /*118*/  "\tBroadcast: NC %d->EN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*119*/  "\tBroadcast: NC %d->NC %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*120*/  "\tBroadcast: NC %d->NN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*121*/  "\tBroadcast: NC %d->BRCST %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"       ,
   /*122*/  "\tBroadcast: NN %d->EN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*123*/  "\tBroadcast: NN %d->NC %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*124*/  "\tBroadcast: NN %d->NN %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"          ,
   /*125*/  "\tBroadcast: NN %d->BRCST %x nbas=%d, cp=%d, pr=%d, tpcBk=%d, prf=%02x, nsym=%d, gcdBM=%08x, CU=%x, clk=0x%x\n"       ,
   /*126*/  "CP is %d\n"                                                                                                         ,
   /*127*/  "%08x %08x %08x %08x %08x %08x %08x %08x\n"                                                                          ,
   /*128*/  "Tx Probe report req: Src=%x, Dst=%x\n"                                                                              ,
   /*129*/  "Rx Probe report req: Src=%x, Dst=%x\n"                                                                              ,
   /*130*/  "Rx Ack: Src=%x, Dst=%x\n"                                                                                           ,
   /*131*/  "Tx Ack: Src=%x, Dst=%x\n"                                                                                           ,
   /*132*/  "Set new TEK key (Seq=%d)\n"                                                                                         ,
   /*133*/  "Set new PMK key (Seq=%d)\n"                                                                                         ,
   /*134*/  "Robust cp mode cp_max=%d cp_min=%d cp_overflow=%d\n"                                                                                                   ,
   /*135*/  "SP_I\n"                                                                                                             ,
   /*136*/  "@ iTBO: S.C=%d, B.B=0x%x, Left.B=0x%x, Right.B=0x%x\n"                                                              ,
   /*137*/  "@ lTBO: S.C=%d, Learned_Bitmask=0x%x\n"                                                                             ,
   /*138*/  "\n MEMCPY_SIZE=%d, MEMCPY_TIME=%d MEMCPY_RATE=%d MEMCPY_COUNT=%d MEMCPY_FULL_CLOCK=%d ERROR=%d \n"                  ,
   /*139*/  "\n MEMSET_SIZE=%d, MEMSET_TIME=%d MEMSET_RATE=%d MEMSET_COUNT=%d MEMSET_MAX=%d \n"                                  ,
   /*140*/  "@ CCOF: HT=%d, UC=%d, BC=%d, MAP=%d, MAP_P1=%d, CFO=%06d, C_SFO=%06d\n"                                             ,
   /*141*/  "Sep Turbo PIII to nid %d\n"                                                                                         ,
   /*142*/  "@ INF2: MAC_CLK=%08x, CPU_Usage=%d, QM_ovrld=%d, TurboMode=%x\n"                                                    ,
   /*143*/  "Beacon locked NID=%d a=%d tg=%d rs=%d\n"                                                                            ,
   /*144*/  "Diversity locked NID=%d a=%d tg=%d rs=%d\n"                                                                         ,
   /*145*/  "Resync completed OK - on NC ID=%d, Lost Beacons (from new NC)=%d, Lost MAPs (from new NC)=%d\n"                     ,
   /*146*/  "Tx PwrCtrl: nid=%d\n"                                                                                               ,
   /*147*/  "Error handling control frame. subType=%d, data=%08x,%08x,%08x\n"                                                    ,
   /*148*/  "\n\\Resync fail as NN. BH Mode=%d, Lost Beacons (from new NC)=%d, Lost MAPs (from new NC)=%d\n"                     ,
   /*149*/  "\n\\Resync fail as EN. BH Mode=%d, Lost Beacons (from new NC)=%d, Lost MAPs (from new NC)=%d\n"                     ,
   /*150*/  "Enabling HW AGC due to probe 1 to nodeID=%d\n"                     ,
   /*
   * MLME additional lines
   */

}; 


char *moca_core_lab_MAC_strings[] = {
   /*00*/   "Add Au: freeDesc  %d ScheduledCtrl %d RxCtrlInCycle %d reserveDesc %d\n"                             ,
   /*01*/   "Node %d: Offset %d\n"                                                                                ,
   /*02*/   "NULL on DMA_MOCA_RX\n"                                                                               ,
   /*03*/   "NULL on DMA_GMII_TX (%d)\n"                                                                          ,
   /*04*/   "Error 120:%x\n"                                                                                      ,
   /*05*/   "Resync completed OK\n"                                                                               ,
   /*06*/   "handoff to EN-ONLY node\n"                                                                           ,
   /*07*/   "\n\\Start handoff as new NC\n"                                                                       ,
   /*08*/   "Start handoff as NN. Drop\n"                                                                         ,
   /*09*/   "Start handoff as EN. Expected new NC: %d\n"                                                          ,
   /*10*/   " Miss! \n"                                                                                           ,
   /*11*/   "Error DBG1: %x\n"                                                                                    ,
   /*12*/   "Error DBG2: %x\n"                                                                                    ,
   /*13*/   "\nCreateMap: Add ACF %x\n"                                                                           ,
   /*14*/   "Start handoff as old NC\n"                                                                           ,
   /*15*/   "Allocate extra probe to node %x\n"                                                                   ,
   /*16*/   "Sanity error on line: %d\n"                                                                          ,
   /*17*/   "&\n"                                                                                                 ,
   /*18*/   "LS ->Deprecate %x\n"                                                                                 ,
   /*19*/   "MAC: ANB Remove node [to <- from]: 0x%08X\n"                                                         ,
   /*20*/   "\nPROTOCOL_IE filter\n"                                                                              ,
   /*21*/   "\nTIME_ALLOCATION_IE filter\n"                                                                       ,
   /*22*/   "Filter Probe Rx %x\n"                                                                                ,
   /*23*/   "Filter LC: %x\n"                                                                                     ,
   /*24*/   "Filter Rx from non ANB node: 0x%X\n"                                                                 ,
   /*25*/   "Filter Rx:%x\n"                                                                                      ,
   /*26*/   "No Phy profile. Skip\n"                                                                              ,
   /*27*/   "Stop Allocating AUs\n"                                                                               ,
   /*28*/   "\nL%8x\n"                                                                                            ,
   /*29*/   "\nPROTOCOL_IE parse\n"                                                                               ,
   /*30*/   "\nTIME_ALLOCATION_IE parse\n"                                                                        ,
   /*31*/   "Time drift error: %d uSec\n"                                                                         ,
   /*32*/   "Error diff %d"                                                                                       ,
   /*33*/   "Error CPU overload, Aborting\n"                                                                      ,
   /*34*/   "Null on DMA %d\n"                                                                                    ,
   /*35*/   "E15601:0x%x\n"                                                                                       ,
   /*36*/   "O\n"                                                                                                 ,
   /*37*/   "Error 15602:0x%x\n"                                                                                  ,
   /*38*/   "Error 11401:%x\n"                                                                                    ,
   /*39*/   "Create IE RE\n"                                                                                      ,
   /*40*/   "Error 11402: 0x%x\n"                                                                                 ,
   /*41*/   "0x%x\n"                                                                                              ,
   /*42*/   "W: Stop allocate REs (%d)\n"                                                                         ,
   /*43*/   "Parse IE RE\n"                                                                                       ,
   /*44*/   "Error 11701:0x%x\n"                                                                                  ,
   /*45*/   "Tout\n"                                                                                              ,
   /*46*/   "MATCH %d\n"                                                                                          ,
   /*47*/   "NO_MATCH %d\n"                                                                                       ,
   /*48*/   "Error: %d\n"                                                                                         ,
   /*49*/   "Error 162:0x%x\n"                                                                                    ,
   /*50*/   "Resync completed OK\n"                                                                               ,
   /*51*/   "Network Lost. Restart admission (reason 0x%X)\n"                                                     ,
   /*52*/   "Drop LC %x\n"                                                                                        ,
   /*53*/   "Resync completed OK\n"                                                                               ,
   /*54*/   "Error enqueue pkt with QID %d\n"                                                                     ,
   /*55*/   "Flip_ERR:%d[ts]\n"                                                                                   ,
   /*56*/   "?r%X\n"                                                                                              ,
   /*57*/   "?l%X\n"                                                                                              ,
   /*58*/   "?c%X\n"                                                                                              ,
   /*59*/   "?e%X\n"                                                                                              ,
   /*60*/   "?g%X\n"                                                                                              ,
   /*61*/   "?b%X\n"                                                                                              ,
   /*62*/   "?m%X\n"                                                                                              ,
   /*63*/   "?R%X\n"                                                                                              ,
   /*64*/   "$r%X\n"                                                                                              ,
   /*65*/   "$l%X\n"                                                                                              ,
   /*66*/   "$c%X\n"                                                                                              ,
   /*67*/   "$e%X\n"                                                                                              ,
   /*68*/   "$g%X\n"                                                                                              ,
   /*69*/   "$b%X\n"                                                                                              ,
   /*70*/   "$m%X\n"                                                                                              ,
   /*71*/   "$R%X\n"                                                                                              ,
   /*72*/   "&B%X\n"                                                                                              ,
   /*73*/   "&M%X\n"                                                                                              ,
   /*74*/   "!m%X\n"                                                                                              ,
   /*75*/   "!b%X\n"                                                                                              , 
   /*76*/   "Flip delay 0x%x[ts]\n"                                                                               ,
   /*77*/   "Skipping too close Beacon\n"                                                                         ,
   /*78*/   "Modify RO from unavailable node ID (nodeID|ANB = 0x%X)\n"                                            ,
   /*79*/   "Stop Alloc Data/CTRL on CreateMap\n"                                                                 ,
   /*80*/   "Drop packet from inactive node\n"                                                                    ,
   /*81*/   "Received beacon from adjacent channel during NS. Stop searching current window.\n"                   ,
   /*82*/   "Set propagation delay - Node ID=%d ; Old=%hd ; New=%hd (-1 is Uninitialized)\n"                      ,
   /*83*/   "Remove node 0x%X due to unusable channel\n"                                                          ,
   /*84*/   "NC ID changed during resync for NN...\n"                                                             ,
   /*85*/   "LC:%08x\n"                                                                                           ,
   /*86*/   "Flip Post Err:%d\n"                                                                                  , 
   /*87*/   "CRC On Admission Request..\n"                                                                        ,
   /*88*/   "Last MAP parsing not ended. Schedule standard rcv window instead of extended window.\n"              ,
};

char *moca_core_lab_PHY_strings[] = {
   /*00*/   "Use Probe II CFO=%d\n"                                                                               ,
   /*01*/   "Ref_Table: %d %d %d %d %d\n"                                                                         ,
   /*02*/   "Pilots: {%d,%d %d,%d %d,%d %d,%d %d,%d %d,%d %d,%d %d,%d}\n"                                         ,
   /*03*/   "GARPL (%d) > FIRST_RLAPM_THRESHOLD (%d) ==> RLAPM (%d) \n"                                           ,
   /*04*/   "GARPL (%d) < LAST_RLAPM_THRESHOLD (%d) ==> RLAPM (%d) \n"                                            ,
   /*05*/   "GARPL (%d) ==> RLAPM*2 (%d) \n"                                                                      ,
   /*06*/   "Error Missing probe preamble= %d src=%d desc=%d\n"                                                   ,
   /*07*/   "@ Probe II results: teta=%x, rho=%x, scaleQ=%d, num_probes=%d, score=%x%08x, cfo=%d Hz\n"            ,
   /*08*/   "<<<<RA=%x\n"                                                                                         ,
   /*09*/   "irs=%x\n"                                                                                            ,
   /*10*/   "to=%x\n"                                                                                             ,
   /*11*/   "&\n"                                                                                                 ,
   /*12*/   "px%c\n"                                                                                              ,
   /*13*/   "p%c\n"                                                                                               ,
   /*14*/   "$p%x\n"                                                                                              ,
   /*15*/   "$P%x\n"                                                                                              ,
   /*16*/   "p%c\n"                                                                                               ,
   /*17*/   "OutPwr=%d,OutRefPwr=%d,Delta=%d,Pad_gc=%x,ActualTxGainTblIdx=%d,FinalPwr=%x\n"                       ,
   /*18*/   "Error: Fc_I out of range! Setting default values\n\n"                                                ,
   /*19*/   "TX LPF Go=%d,Gn=%d,Fc_I=%d\n\n"                                                                      ,
   /*20*/   "RX LPF Go=%d,Gn=%d,Fc_I=%d\n\n"                                                                      ,
   /*21*/   "@ Calib:IdcSave=%d,QdcSavef=%d,Ploft=%d,\n"                                                          ,
   /*22*/   "ASave=%d,BSave=%d,Piq=%d,\n"                                                                         ,
   /*23*/   "maxNbas=%d, desired=%d, cp=%d, allowedB=%d bo_range=%d snr_avg=%d\n"                                 ,
   /*24*/   "%08x %08x %08x %08x %08x %08x %08x %08x \n"                                                          ,
   /*25*/   ";%08d %08d;\n"                                                                                       ,
   /*26*/   "old_gain=%d rssi=%d "                                                                                ,
   /*27*/   "Calibration TimeOut\n"                                                                               ,
   /*28*/   ";nodeID=%d  MAC=%02X:%02X:%02X:%02X:%02X:%02X;\n"                                                    ,
   /*29*/   ";*********************************************;\n"                                                   ,
   /*30*/   "%08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x \n",
   /*31*/   "%08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x %08x\n"                   ,
   /*32*/   "%08x %08x %08x %08x %08x %08x %08x %08x\n"                                                           ,
   /*33*/   "OTF: Initial g_GpEnd = %x\n"                                                                         ,
   /*34*/   "OTF: Measured Power = %x, RefValue=%x, Delta=%x\n"                                                   ,
   /*35*/   "OTF: Final g_GpEnd = %x\n"                                                                           ,
   /*36*/   "OTF: FINE_MODE: OutPwr=%x,OutRefPwr=%x,Delta=%x,g_GpEnd=%x\n"                                        ,
   /*37*/   "missed_rssi=%x\n"                                                                                    ,
   /*38*/   "freq_lock=%d\n"                                                                                      ,
   /*39*/   "NOT IN USE\n"                                                                                        ,
   /*40*/   "Setting tank to %d\n"                                                                                ,
   /*41*/   "Tank is set  to %d\n"                                                                                ,
   /*42*/   "cap_cntl=%d\n"                                                                                       ,
   /*43*/   "RSSI exception=%d\n"                                                                                 ,
   /*44*/   "Update gain=%x\n"                                                                                    ,
   /*45*/   "Do not Update gain=%x\n"                                                                                    ,
   /*46*/   "current:  bo=%d  sign=%d  state=%d     \n"                                              ,
   /*47*/   "new:      desrable_nbas=%d calc_nbas=%d  relative=%d  state=%d     \n"                                              ,



};

char *moca_core_lab_QM_strings[] = {
   /*00*/   "Broken packet on DMA %d\n"                                                                           ,
   /*01*/   "Stop DMA %x\n"                                                                                       ,
   /*02*/   "Enable DMA %x\n"                                                                                     ,
   /*03*/   ""                                                                                                    ,  // Not used
   /*04*/   "Restart DMA %x\n"                                                                                    ,
   /*05*/   "NULL desc on DMA %d\n"                                                                               ,
   /*06*/   "\nDMA_GMII_TX: CHSRV=%x Head=%x Tail=%x \n"                                                          ,
};

char *moca_core_lab_L2_strings[] = {
   /*00*/   "L2 %d\n"                                                                                             ,
   /*01*/   "Starting MR transaction as entry node.\nEntry node=%d, waveBitmask=0x%x, transType=%d, transSubtype=%d, nonDefaultSeq=%d, resetStatus=%d, resetTime=%d\n" ,
   /*02*/   "Send reset request\n"                                                                                ,
   /*03*/   "Send complete message\n"                                                                             ,
   /*04*/   "Send response message\n",
};

StringsArray_T moca_core_lab_strings[MOCA_STR_LAYER_LAST] = {
   {moca_core_lab_GENERAL_strings,  sizeof(moca_core_lab_GENERAL_strings)  / sizeof(unsigned int) }   ,
   {moca_core_lab_MLME_strings,     sizeof(moca_core_lab_MLME_strings)     / sizeof(unsigned int) }   ,
   {moca_core_lab_HOST_MMP_strings, sizeof(moca_core_lab_HOST_MMP_strings) / sizeof(unsigned int) }   ,
   {moca_core_lab_PHY_strings,      sizeof(moca_core_lab_PHY_strings)      / sizeof(unsigned int) }   ,
   {moca_core_lab_MAC_strings,      sizeof(moca_core_lab_MAC_strings)      / sizeof(unsigned int) }   ,
   {moca_core_lab_DME_strings,      sizeof(moca_core_lab_DME_strings)      / sizeof(unsigned int) }   ,
   {moca_core_lab_ECL_strings,      sizeof(moca_core_lab_ECL_strings)      / sizeof(unsigned int) }   ,
   {moca_core_lab_QM_strings,       sizeof(moca_core_lab_QM_strings)       / sizeof(unsigned int) }   ,
   {moca_core_lab_L2_strings,       sizeof(moca_core_lab_L2_strings)       / sizeof(unsigned int) }
};
#else
extern char *moca_core_lab_GENERAL_strings[];
extern char *moca_core_lab_DME_strings[];
extern char *moca_core_lab_HOST_MMP_strings[];
extern char *moca_core_lab_ECL_strings[];
extern char *moca_core_lab_MLME_strings[];
extern char *moca_core_lab_MAC_strings[];
extern char *moca_core_lab_PHY_strings[];
extern char *moca_core_lab_QM_strings[];
extern char *moca_core_lab_L2_strings[];
extern StringsArray_T moca_core_lab_strings[MOCA_STR_LAYER_LAST];
#endif


