# File: bcmdrivers/opensource/char/tzdrv/tzioc_tdrv/impl1/Makefile
#
# Makefile for the tzioc_tdrv driver
#

obj-m += tzioc_tdrv.o

astra_subdir=$(BUILD_DIR)/secureos/astra

EXTRA_CFLAGS += \
	-I$(src) \
	-I$(astra_subdir)/common/include \
	-I$(src)/../../bcm_astra/bcm9$(BRCM_CHIP)


