#!/bin/sh
MEDIA=${1}
CHIP=${2}
PROFILE_DIR=${3}
MAX_BTLDR_SIZE=${4}
SECIMAGE=${5}
IMAGE=${6}
IMAGE_SPI=${7:-"$0_invalid_file_"} # an image withou sec prefix - ony for spi

#echo "Parms : $0 $1 $2 $3 $4 $5 $6 $7" 
print_help()                                                                                                                      
{
        echo "usage: $0 <spi> <63138 | 63148 | 6838 | 63381> <profile_dir> <btldr_max_size> <secimage> <image_in> <image_spi>" 
}

#$1 program                                                                                                                       
#$2 message
exit_on_error()                                                                                                                   
{
        echo "$1 : ERROR $2"                                                                                                      
        print_help
        exit 1
}

# Sanity check for the input                                                                                                          
[ $# -lt 6 ] || [ $# -gt 7 ] && exit_on_error $0 "Invalid number of parameters"
[ $# -eq 7 ] && [ "${MEDIA}" != "spi" ] && exit_on_error $0 "${MEDIA} not supported"
[ "${MEDIA}" == "spi" ] && [ -z ${IMAGE_SPI} ] && exit_on_error $0 "${IMAGE_SPI} is not existing"
[ "${MEDIA}" == "spi" ] && [ ! -f ${IMAGE_SPI} ] && exit_on_error $0 "${IMAGE_SPI} is not existing"
[ ! -d ${PROFILE_DIR} ] || [ ! -f ${IMAGE} ] && exit_on_error $0 "${IMAGE} or ${PROFILE_DIR} are not existing"
[[ _63138_63148_6838_63381_ != *_${CHIP}_* ]] && exit_on_error $0 "${CHIP} not supported"



base_bld_dir=$PROFILE_DIR/../..
base_btrm_dir=$base_bld_dir/cfe/cfe/board/bcm63xx_btrm
base_data_dir=$base_btrm_dir/data
data_dir=$base_data_dir/${CHIP}
btldr_dir=$base_bld_dir/targets/cfe
hostTools_dir=$base_bld_dir/hostTools
tools_dir=$hostTools_dir/SecureBootUtils

cd $btldr_dir

if [ "${CHIP}" != "63268" ]
then
   # Create the authenticated header ( type, ver, len, config ... all 16 bit)
   # config = 1 if nvram is embedded within SBI, 0 otherwise
   # dec2bin utility converts a decimal number to it's hex 32 bit binary equivalent 
   # The input to dec2bin is a decimal number and cannot by larger than 999999
   # The 4 byte binary is written to ./size.tmp 
   $tools_dir/secutil.pl dec2bin --config=${HOSTTOOLS_DIR}/local_install/conf/${TOOLCHAIN_PREFIX}.conf 0  
   cat ./size.tmp | head --bytes=4 > ./fourbytes.tmp
   cat ./fourbytes.tmp ./fourbytes.tmp > ./authhdr.tmp
   rm -f ./fourbytes.tmp
   rm -f ./size.tmp
   # prepend the authenticated header, chain-of-trust (COT) credentials, and bootloader together
      #cat ./authhdr.tmp $data_dir/mfg.cot.bin $data_dir/mfg.cot.sig $data_dir/op.cot.bin $data_dir/op.cot.sig $btldr_dir/cfesec$2.bin > ./unsigned_cfesbi.tmp
      # The 6838 cfe rom build supports both unsecure and secure boot
      # 63381 secure boot cfe rom build is larger than 16k and therefore has its own image. Legacy cfe63381rom.bin is < 16k because it supports small page nand flash
      # 63138 / 63148 secure boot cfe rom build is larger than 64k and therefore have their own images. 64k pmc mips + unsecure cfe rom has to fit into 128k block 0
      cat ./authhdr.tmp $data_dir/mfg.cot.bin $data_dir/mfg.cot.sig $data_dir/op.cot.bin $data_dir/op.cot.sig $IMAGE > ./unsigned_cfesbi.tmp

   rm -f ./authhdr.tmp

   # sign the entire BI image using the mfg COT element private key
   openssl dgst -sign $base_data_dir/mfg.pem -keyform pem -sha256 -sigopt rsa_padding_mode:pss -sigopt \
      rsa_pss_saltlen:-1 -out ./sig.tmp ./unsigned_cfesbi.tmp
   # Create a CRC across the entire BI image (4 byte crc in binary format will be stored in the file ./crc.tmp)
   # crc2bin expects a local file called unsigned_cfesbi.tmp
   $tools_dir/secutil.pl --config=${HOSTTOOLS_DIR}/local_install/conf/${TOOLCHAIN_PREFIX}.conf crc2bin

   # concatenate the signature and the crc to the end of the BI image
   cat ./unsigned_cfesbi.tmp ./sig.tmp ./crc.tmp > ./signed_cfesbi.tmp
   rm -f ./unsigned_cfesbi.tmp ./sig.tmp ./crc.tmp

   # Get the size of the entire BI image (This is the amount of bytes the btrm will copy into internal mem)
   sbi_size=`wc -c ./signed_cfesbi.tmp | cut -d " " -f1`

   # Increase the sbi_size by the size of the unauthenticated header that will be attached (20 bytes if no padding)
   sbi_size=`expr $sbi_size + 20`

   # Create the unauthenticated header with a crc
   # 64-bit magic number 1st word is (00112233), 2nd word is (00445566)
   # 3rd word is header version (1), 4th word is the sbi_size 
   $tools_dir/secutil.pl dec2bin --config=${HOSTTOOLS_DIR}/local_install/conf/${TOOLCHAIN_PREFIX}.conf 112233  
   cat ./size.tmp | head --bytes=4 > ./first_word.tmp
   $tools_dir/secutil.pl dec2bin --config=${HOSTTOOLS_DIR}/local_install/conf/${TOOLCHAIN_PREFIX}.conf 445566  
   cat ./size.tmp | head --bytes=4 > ./second_word.tmp
   $tools_dir/secutil.pl dec2bin --config=${HOSTTOOLS_DIR}/local_install/conf/${TOOLCHAIN_PREFIX}.conf 1  
   cat ./size.tmp | head --bytes=4 > ./third_word.tmp
   $tools_dir/secutil.pl dec2bin --config=${HOSTTOOLS_DIR}/local_install/conf/${TOOLCHAIN_PREFIX}.conf $sbi_size
   cat ./size.tmp | head --bytes=4 > ./fourth_word.tmp
   cat ./first_word.tmp ./second_word.tmp ./third_word.tmp ./fourth_word.tmp  > ./unsigned_cfesbi.tmp
   $tools_dir/secutil.pl --config=${HOSTTOOLS_DIR}/local_install/conf/${TOOLCHAIN_PREFIX}.conf crc2bin
   cat ./unsigned_cfesbi.tmp ./crc.tmp > ./unauthsbihdr.tmp
   rm -f ./size.tmp ./first_word.tmp ./second_word.tmp ./third_word.tmp ./fourth_word.tmp ./crc.tmp ./unsigned_cfesbi.tmp

   # create the entire bi image (unauth_hdr + auth_hdr + sbi + trailer)
   cat ./unauthsbihdr.tmp ./signed_cfesbi.tmp > ./cfe${CHIP}bi.tmp

   if [ "${MEDIA}" == "spi" ]
   then
      #mv ./cfe${CHIP}bi.bin ./cfe${CHIP}bi.tmp

      # Set up a padding file
      rm -f ./filek.tmp ./newfilek.tmp
      dd if=/dev/zero of=./filek.tmp bs=1k count=512
      tr '\000' '\377' < ./filek.tmp > ./newfilek.tmp

      # Calculate the pad length
      btldr_max_size=`expr $4 \* 1024`
      pad_len=`expr $btldr_max_size / 2`

      # pad out the original headerless cferom (with ram) build and concatenate with bi image
      cat ${IMAGE_SPI} ./newfilek.tmp | head --bytes=$pad_len | cat - ./cfe${CHIP}bi.tmp ./newfilek.tmp | head --bytes=$btldr_max_size > ./cfe${CHIP}bi.bin

      #cleanup
      rm -f ./cfe${CHIP}bi.tmp ./filek.tmp ./newfilek.tmp
   else
      mv  cfe${CHIP}bi.tmp cfe${CHIP}bi.bin    	
   fi

   rm -f ./unauthsbihdr.tmp ./signed_cfesbi.tmp
else

   # 63268 Secure boot build
   # Set up a padding file
   rm -f ./file128k.tmp ./newfile128k.tmp ./cferom.tmp ./bootloader.sig ./cferom_head.tmp ./nvram.tmp ./cferom_tail.tmp
   dd if=/dev/zero of=./file128k.tmp bs=1k count=128

   if [ "${MEDIA}" == "spi" ]
   then
      # Pad 63268 secure boot cferom/ram image out to 128KB
      tr '\000' '\377' < ./file128k.tmp > ./newfile128k.tmp
      cat $IMAGE ./newfile128k.tmp | head --bytes=131072 > ./cferom.tmp
   else
      # Pad 63268 secure boot cferom image out to 48KB
      cat $IMAGE ./file128k.tmp | head --bytes=49152 > ./cferom.tmp
   fi

   # Create a signature across the 48KB / 128 KB padded image.
   openssl dgst -sign $base_data_dir/mfg.pem -keyform pem -sha256 -sigopt rsa_padding_mode:pss -sigopt \
           rsa_pss_saltlen:-1 -out ./bootloader.sig ./cferom.tmp

   # Concatenate all of the security materials into a single file. Should be 1412 bytes in length
   cat ./bootloader.sig $data_dir/mfg.cot.sig $data_dir/mfg.cot.bin | head --bytes=770 | \
   cat - $data_dir/op.cot.sig $data_dir/op.cot.bin | head --bytes=1284 | \
   cat - $data_dir/mfg.ek.enc $data_dir/op.ek.enc $data_dir/mfg.iv.enc $data_dir/op.iv.enc > ./nvram.tmp

   # Chop image into two pieces and remove NVRAM security empty bytes 
   # Security materials in NVRAM start at 0x580+0x400 = 0x980 (2432) bytes into the image
   cat ./cferom.tmp | head --bytes=2432 > ./cferom_head.tmp

   # Security credentials go for 1412 bytes.
   if [ "${CHIP}" == "spi" ]
   then
      # Therefore, the 2nd piece for SPI is: 128KB - 2432 - 1412 = 127228
      cat ./cferom.tmp | tail --bytes=127228 > ./cferom_tail.tmp
   else
      # Therefore, the 2nd piece for NAND is: 48KB - 2432 - 1412 = 45308
      cat ./cferom.tmp | tail --bytes=45308 > ./cferom_tail.tmp
   fi

   # Concatenate the tmp files. If SPI, final file should be 128KB in size; If NAND, then 48KB in size
   cat ./cferom_head.tmp ./nvram.tmp ./cferom_tail.tmp > cfe${CHIP}bin.bin

   # clean up
   rm -f ./file128k.tmp ./newfile128k.tmp ./cferom.tmp ./bootloader.sig ./cferom_head.tmp ./nvram.tmp ./cferom_tail.tmp
fi

# rename BI .bin 
mv ./cfe${CHIP}bi.bin $SECIMAGE 
